M6R0
I/grF_calc_WPsi4R6$%'objectG%&indexG6#%"sG6"F)C$>8$&%3grG_Cbdnbdnbdnbdn_G6'%/gr
G_metricNameG""#""%F1F2-%'RETURNG6#F,F)F)F)F),
I0grF_calc_NPbetaRF$F'F)F)C$>F,,&&%2grG_rotbdnbdnbdn_G6&F0F1"""""$#F>F1&F<6&F0F
?F2F?F@F3F)F)F)F),
I1grF_calc_RLambdaRF$F'F)F)C$>F,,&&%-grG_Rbdnbdn_G6%F0F>F1#F>"#7&FI6%F0F?F2#!""
FL-F46#,$F,FPF)F)F)F),
I+grG_newObj=F)%&falseGE\[lfq%'RPhi12G=F)FVE\[l%%0grC_displayNameG%&Phi12G%+grC
_calcFnG%0grF_calc_RPhi12G%,grC_dependsG<#-%"RG6$%$bdnGF^o%,grC_useWhenG%.grF_w
hen_RPhiG%(CtaubarG=F)FVE\[l)%,grC_rootStrG%'taubarG%.grC_indexListG7"Fgn%2grF_
calcConjugateGFin<#%%CtauG%-grC_symmetryG%/grF_sym_scalarG%+grC_headerG%<NP~Spi
n~Coefficient,~taubarG%0grC_calcFnParmsG7#Fjo%)grC_rootG%*NPtaubar_G%&Phi11G=F)
FVE\[l+FenFcpFdoFcpFfoFgoFgn%1grF_calc_NPPhi11GFin<7%(NPkappaG%(NPsigmaG%%NPnuG
%&NPrhoG%%NPmuG%&NPtauG%%NPpiG%(NPgammaG%(NPalphaG%)NPlambdaG%*NPepsilonG%)NPrh
obarG%)NPtaubarG%+NPgammabarG%+NPalphabarG%*NPbetabarG%'NPbetaG%(NPmubarG%(NPpi
barG%-NPepsilonbarG-%"eG6$F^o%#upGF[pF\p%/grC_attributesG<#%5use_diff_constrain
t_GF]p%4Ricci~Scalar,~Phi11GF_pFgoFap%)NPPhi11_G%$CmuG=F)FVE\[l)Fdo%#muGFfoFgoF
gn%-grF_calc_CmuGFin<&%%detbG-F]r6$F^o%#dnG-F]r6%F^oF^s%$pdnG-%&LevCSG6&F_rF_rF
_rF_rF[pF\pF]p%8NP~Spin~Coefficient,~muGF_pFgoFap%&NPmu_G%*CgammabarG=F)FVE\[l)
Fdo%)gammabarGFfoFgoFgnFhoFin<#%'CgammaGF[pF\pF]p%>NP~Spin~Coefficient,~gammaba
rGF_p7#F\tFap%,NPgammabar_G%'CPhi00G=F)FVE\[l)Fdo%&Phi00GFfoFgoFgn%0grF_calc_CP
hi00GFin<)%)CepsilonGF[s%'CkappaG%%CrhoGFbs%'CalphaG-%%DCFqG6$F^sFasF[pF\pF]p%4
Ricci~Scalar,~Phi00GF_pFgoFap%)NPPhi00_G%)CPsi4barG=F)FVE\[l)Fdo%(Psi4barGFfoFg
oFgnFhoFin<#%&CPsi4GF[pF\pF]p%5Weyl~Scalar,~Psi4barGF_p7#FduFap%)Psi4bar_G%&CPs
i2G=F)FVE\[l)Fdo%%Psi2GFfoFgoFgn%/grF_calc_CPsi2GFin<0F[s%(ClambdaGFgt%'CsigmaG
FhtFjoFbs%$CnuGFer%$CpiGF\tFitFjt-%%DCFrGF\uF[pF\pF]p%2Weyl~Scalar,~Psi2GF_pFgo
Fap%&Psi2_GF[s=F)FVE\[l(Fdo%#b~GFfoFgoFin<"F[pF\p%.grC_preCalcFnG%.grF_calc_det
bGF]p%9Determinant~of~the~basisGFap%&detb_G%&Phi20G=F)FVE\[l*FenF^wFdoF^wFfoFgo
FgnFhoFin<#%&Phi02GF[pF\pF]p%4Ricci~Scalar,~Phi20GF_p7#FbwFap%)NPPhi20_G%'Cpiba
rG=F)FVE\[l)Fdo%&pibarGFfoFgoFgnFhoFin<#FavF[pF\pF]p%;NP~Spin~Coefficient,~piba
rGF_p7#FavFap%)NPpibar_GF`v=F)FVE\[l)Fdo%#nuGFfoFgoFgn%-grF_calc_CnuGFinFjrF[pF
\pF]p%8NP~Spin~Coefficient,~nuGF_pFgoFap%&NPnu_GFeq=F)FVE\[l)FdoFjsFfoFgoFgnFho
Fin<#F_qF[pF\pF]pF]tF_p7#F_qFapF_t%)CPsi2barG=F)FVE\[l)Fdo%(Psi2barGFfoFgoFgnFh
oFin<#FhuF[pF\pF]p%5Weyl~Scalar,~Psi2barGF_p7#FhuFap%)Psi2bar_G%'CPhi02G=F)FVE\
[l)FdoFbwFfoFgoFgn%0grF_calc_CPhi02GFin<)F[sF_vFjoFbsF\t%&CbetaGFjtF[pF\pF]p%4R
icci~Scalar,~Phi02GF_pFgoFap%)NPPhi02_G%*CalphabarG=F)FVE\[l)Fdo%)alphabarGFfoF
goFgnFhoFin<#FitF[pF\pF]p%>NP~Spin~Coefficient,~alphabarGF_p7#FitFap%,NPalphaba
r_G%+NPkappabarG=F)FVE\[l)Fdo%)kappabarGFfoFgoFgnFhoFin<#FhpF[pF\pF]p%>NP~Spin~
Coefficient,~kappabarGF_p7#FhpFap%,NPkappabar_G%&WPsi4G=F)FVE\[l%Fen%%Psi4GFgnF
"Fin<#-%"CG6&F^oF^oF^oF^oF_o%.grF_when_WPsiG-%$DCFG6$%$bupGFd[l=F)FVE\[l*Fdo%&s
igmaGFfo7$Fd[lFd[lFgn%-grF_calc_DCFGFin<.FftF^vFgtF_vFhtFjoF`vFerFavF\tFitFeyF[
p%/grF_sym_nosym2GFjv%0grF_precalc_DCFGF]p%EDebever~connection~forms,~sigma(a,b
)GF_pFgoFap%+DCFbupbup_G%%Psi1G=F)FVE\[l*FdoF_\lFfoFgoFgn%.grF_calc_Psi1GFin</F
hpFipF\qF^qF_qF`qFbqFcqFfqFhqFjqF[rF\rF[pF\pF`rFarF]p%5Weyl~Scalar,~NP~Psi1GF_p
FgoFap%&Psi1_G%'PetrovG=F)FVE\[l)Fdo%-Petrov~Type~GFfoFgoFgn%0grF_calc_PetrovGF
in<'%%Psi0GF_\lF[v%%Psi3GF[[lF[pF\pF]p%,Petrov~TypeGF_pFgoFap%(Petrov_GF^q=F)FV
E\[l)Fdo%#piGFfoFgoFgn%.grF_calc_NPpiGFin<#-%$rotG6%F^oF^oF^oF[pF\pF]p%8NP~Spin
~Coefficient,~piGF_pFgoFap%&NPpi_G%(RLambdaG=F)FVE\[l%Fen%)NPLambdaGFgnFCFinFjn
F_oF`oFhp=F)FVE\[l)Fdo%&kappaGFfoFgoFgn%1grF_calc_NPkappaGFinFd]lF[pF\pF]p%;NP~
Spin~Coefficient,~kappaGF_pFgoFap%)NPkappa_GFfn=F)FVE\[l+FenFfnFdoFfnFfoFgoFgn%
1grF_calc_NPPhi12GFin</FipFjpF\qF]qF_qF`qFbq%,NPlambdabarGFeqFfqFhq%(NPnubarGF\
rF[pF\pF`rFarF]p%4Ricci~Scalar,~Phi12GF_pFgoFap%)NPPhi12_G%&Phi21G=F)FVE\[l*Fen
F\_lFdoF\_lFfoFgoFgnFhoFin<#FfnF[pF\pF]p%4Ricci~Scalar,~Phi21GF_p7#FfnFap%)NPPh
i21_G%'CPhi12G=F)FVE\[l)FdoFfnFfoFgoFgn%0grF_calc_CPhi12GFin<)F[sF_vFjoFbsF`vFe
rFbvF[pF\pF]pFj^lF_pFgoFapF[_l%'RPhi00G=F)FVE\[l%FenFctFgn%0grF_calc_RPhi00GFin
FjnF_oF`oF[r=F)FVE\[l)Fdo%+epsilonbarGFfoFgoFgnFhoFin<#FbqF[pF\pF]p%@NP~Spin~Co
efficient,~epsilonbarGF_p7#FbqFap%.NPepsilonbar_G%)CbetabarG=F)FVE\[l)Fdo%(beta
barGFfoFgoFgnFhoFin<#FeyF[pF\pF]p%=NP~Spin~Coefficient,~betabarGF_p7#FeyFap%+NP
betabar_GFiq=F)FVE\[l)Fdo%&mubarGFfoFgoFgnFhoFin<#F\qF[pF\pF]p%;NP~Spin~Coeffic
ient,~mubarGF_p7#F\qFap%)NPmubar_G%&CPsi0G=F)FVE\[l)FdoF\]lFfoFgoFgn%/grF_calc_
CPsi0GFin<)FftF[sFgtF_vFbsFeyFjtF[pF\pF]p%2Weyl~Scalar,~Psi0GF_pFgoFap%&Psi0_GF
cq=F)FVE\[l)Fdo%'rhobarGFfoFgoFgnFhoFin<#F[qF[pF\pF]p%<NP~Spin~Coefficient,~rho
barGF_p7#F[qFap%*NPrhobar_G%&Phi22G=F)FVE\[l+FenF`blFdoF`blFfoFgoFgn%1grF_calc_
NPPhi22GFin<.FjpF\qF]qF^qF_qFaqFh^lFeqFfqFhqFi^lF\rF[pF\pF`rFarF]p%4Ricci~Scala
r,~Phi22GF_pFgoFap%)NPPhi22_G%)CPsi0barG=F)FVE\[l)Fdo%(Psi0barGFfoFgoFgnFhoFin<
#FbalF[pF\pF]p%5Weyl~Scalar,~Psi0barGF_p7#F\]lFap%)Psi0bar_G%'RPhi01G=F)FVE\[l%
Fen%&Phi01GFgn%0grF_calc_RPhi01GFinFjnF_oF`oFbcl=F)FVE\[l+FenFbclFdoFbclFfoFgoF
gn%1grF_calc_NPPhi01GFin</FhpFipFbqF`zFh^lFcqFeqFfqFgqFhqFjqF[rF\rF[pF\pF`rFarF
]p%4Ricci~Scalar,~Phi01GF_pFgoFap%)NPPhi01_GFjbl=F)FVE\[l)FdoFjblFfoFgoFgnFhoFi
n<#F\]lF[pF\pF]p%8Weyl~Scalar,~NP~Psi0barGF_pF]clFapF^cl%&WPsi1G=F)FVE\[l%FenF_
\lFgn%/grF_calc_WPsi1GFinF\[lF_oF`[lF`q=F)FVE\[l)Fdo%&alphaGFfoFgoFgn%1grF_calc
_NPalphaGFinFd]lF[pF\pF]p%;NP~Spin~Coefficient,~alphaGF_pFgoFap%)NPalpha_GF\q=F
)FVE\[l)FdoFhrFfoFgoFgn%.grF_calc_NPmuGFinFd]lF[pF\pF]pFesF_pFgoFapFfs%'CRicciG
=F)FVE\[l)FdoF]^lFfoFgoFgn%0grF_calc_DRicciGFinF]vF[pF\pF]p%<NPLambda~:=~Ricci~
Scalar/24GF_pFgoFap%*NPLambda_GFbw=F)FVE\[l+FenFbwFdoFbwFfoFgoFgn%1grF_calc_NPP
hi02GFin<.FhpFipFbqFh^lFcqFfqFhqFi^lFiqFjqF[rF\rF[pF\pF`rFarF]pFfyF_pFgoFapFgyF
av=F)FVE\[l)FdoFb]lFfoFgoFgn%-grF_calc_CpiGFinFjrF[pF\pF]pFh]lF_pFgoFapFi]l%&WP
si2G=F)FVE\[l%FenF[vFgn%/grF_calc_WPsi2GFinF\[lF_oF`[l%(Psi1barG=F)FVE\[l)FdoF\
flFfoFgoFgnFhoFin<#F_\lF[pF\pF]p%8Weyl~Scalar,~NP~Psi1barGF_p7#F_\lFap%)Psi1bar
_GFaq=F)FVE\[l)Fdo%'lambdaGFfoFgoFgn%2grF_calc_NPlambdaGFinFd]lF[pF\pF]p%<NP~Sp
in~Coefficient,~lambdaGF_pFgoFap%*NPlambda_GF]^l=F)FVE\[l+FenF]^lFdoF]^lFfoFgoF
gn%2grF_calc_NPLambdaGFinFgpF[pF\pF`rFarF]pF_elF_pFgoFapF`elFfq=F)FVE\[l)FdoF[z
FfoFgoFgnFhoFin<#F`qF[pF\pF]pF]zF_p7#F`qFapF_zF\]l=F)FVE\[l*FdoF\]lFfoFgoFgn%.g
rF_calc_Psi0GFin<-FhpFipF[qF]qFbqFcqFfqFhqFjqF[rF\rF[pF\pF`rFarF]p%5Weyl~Scalar
,~NP~Psi0GF_pFgoFapFhalF_q=F)FVE\[l)Fdo%&gammaGFfoFgoFgn%1grF_calc_NPgammaGFinF
d]lF[pF\pF]p%;NP~Spin~Coefficient,~gammaGF_pFgoFap%)NPgamma_GFht=F)FVE\[l)Fdo%$
rhoGFfoFgoFgn%.grF_calc_CrhoGFinFjrF[pF\pF]p%9NP~Spin~Coefficient,~rhoGF_pFgoFa
p%'NPrho_GFhq=F)FVE\[l)Fdo%%betaGFfoFgoFgnF6FinFd]lF[pF\pF]p%:NP~Spin~Coefficie
nt,~betaGF_pFgoFap%(NPbeta_G-%%CrotGFg]l=F)FVE\[l%FenFe]lFgn%7grF_calc_Crotbdnb
dnbdnGFin<#-F^vFg]lF_o%7grF_when_CrotbdnbdnbdnGF[y=F)FVE\[l)FdoF[yFfoFgoFgnFhoF
in<#F[vF[pF\pF]p%8Weyl~Scalar,~NP~Psi2barGF_p7#F[vFapF_y%&WPsi3G=F)FVE\[l%FenF]
]lFgn%/grF_calc_WPsi3GFinF\[lF_oF`[lF[v=F)FVE\[l*FdoF[vFfoFgoFgn%.grF_calc_Psi2
GFinFgpF[pF\pF`rFarF]p%5Weyl~Scalar,~NP~Psi2GF_pFgoFapFevFjo=F)FVE\[l)Fdo%$tauG
FfoFgoFgn%.grF_calc_CtauGFinFjrF[pF\pF]p%9NP~Spin~Coefficient,~tauGF_pFgoFap%'N
Ptau_G%*CkappabarG=F)FVE\[l)FdoFczFfoFgoFgnFhoFin<#FgtF[pF\pF]pFezF_p7#FgtFapFg
zFjq=F)FVE\[l)FdoFiwFfoFgoFgnFhoFin<#F^qF[pF\pF]pF[xF_p7#F^qFapF]x%&CPsi3G=F)FV
E\[l)FdoF]]lFfoFgoFgn%/grF_calc_CPsi3GFin<)F[sF^vFhtFjoFbsF`vFbvF[pF\pF]p%2Weyl
~Scalar,~Psi3GF_pFgoFap%&Psi3_G-F[u6#F^s=F)FVE\[l)Fdo%#q~GFfo7#F^sFgn%0grF_calc
_DCFqdnGFin<$F\sFa[lF[p%/grF_sym_vectorGF]p%;Debever~connection~form,~qGF_pFgoF
ap%(DCFqdn_G%)CPsi3barG=F)FVE\[l)Fdo%(Psi3barGFfoFgoFgnFhoFin<#FjjlF[pF\pF]p%5W
eyl~Scalar,~Psi3barGF_p7#FjjlFap%)Psi3bar_GFjp=F)FVE\[l)FdoF`xFfoFgoFgn%.grF_ca
lc_NPnuGFinFd]lF[pF\pF]pFbxF_pFgoFapFcxF^v=F)FVE\[l)FdoFeflFfoFgoFgn%1grF_calc_
ClambdaGFinFjrF[pF\pF]pFgflF_pFgoFapFhfl%'CPhi20G=F)FVE\[l)FdoF^wFfoFgoFgnFhoFi
n<#F`yF[pF\pF]pFcwF_p7#F`yFapFew%+NPsigmabarG=F)FVE\[l)Fdo%)sigmabarGFfoFgoFgnF
hoFin<#FipF[pF\pF]p%>NP~Spin~Coefficient,~sigmabarGF_p7#FipFap%,NPsigmabar_G%'C
Phi01G=F)FVE\[l)FdoFbclFfoFgoFgn%0grF_calc_CPhi01GFin<*FftF[sFgtFjoFbsF\t%&CPsi
1GFjtF[pF\pF]pFhclF_pFgoFapFiclF]]l=F)FVE\[l*FdoF]]lFfoFgoFgn%.grF_calc_Psi3GFi
n</FjpF[qF]qF_qF`qFaqFbqFdqFeqFgqFhqFiqF\rF[pF\pF`rFarF]p%5Weyl~Scalar,~NP~Psi3
GF_pFgoFapF`[mF_\m=F)FVE\[l)FdoF_\mFfoFgoFgnFhoFin<#F]]lF[pF\pF]p%8Weyl~Scalar,
~NP~Psi3barGF_p7#F]]lFapFc\mFdq=F)FVE\[l)FdoFeoFfoFgoFgnFhoFin<#F]qF[pF\pF]pF^p
F_p7#F]qFapFbp%*CsigmabarG=F)FVE\[l)FdoFb]mFfoFgoFgnFhoFin<#F_vF[pF\pF]pFd]mF_p
7#F_vFapFf]mFbq=F)FVE\[l)Fdo%(epsilonGFfoFgoFgn%3grF_calc_NPepsilonGFinFd]lF[pF
\pF]p%=NP~Spin~Coefficient,~epsilonGF_pFgoFap%+NPepsilon_GF_v=F)FVE\[l)FdoFg[lF
foFgoFgn%0grF_calc_CsigmaGFinFjrF[pF\pF]p%;NP~Spin~Coefficient,~sigmaGF_pFgoFap
%)NPsigma_GFgt=F)FVE\[l)FdoF`^lFfoFgoFgn%0grF_calc_CkappaGFinFjrF[pF\pF]pFb^lF_
pFgoFapFc^l-FcvFb[m=F)FVE\[l)Fdo%#r~GFfoFf[mFgn%0grF_calc_DCFrdnGFinFh[mF[pFi[m
F]p%;Debever~connection~form,~rGF_pFgoFap%(DCFrdn_G%'RPhi22G=F)FVE\[l%FenF`blFg
n%0grF_calc_RPhi22GFinFjnF_oF`o%'CPhi21G=F)FVE\[l)FdoF\_lFfoFgoFgnFhoFin<#Fi`mF
[pF\pF]pF`_lF_p7#Fi`mFapFb_l%'CnubarG=F)FVE\[l)Fdo%&nubarGFfoFgoFgnFhoFin<#F`vF
[pF\pF]p%;NP~Spin~Coefficient,~nubarGF_p7#F`vFap%)NPnubar_G%'CPhi10G=F)FVE\[l)F
do%&Phi10GFfoFgoFgnFhoFin<#Fg]mF[pF\pF]p%4Ricci~Scalar,~Phi10GF_p7#Fg]mFap%)NPP
hi10_G-%%DCFpGFb[m=F)FVE\[l)Fdo%#p~GFfoFf[mFgn%0grF_calc_DCFpdnGFinFh[mF[pFi[mF
]p%;Debever~connection~form,~pGF_pFgoFap%(DCFpdn_GFbu=F)FVE\[l)FdoFbuFfoFgoFgnF
hoFin<#F[[lF[pF\pF]p%8Weyl~Scalar,~NP~Psi4barGF_p7#F[[lFapFguF[[l=F)FVE\[l*FdoF
[[lFfoFgoFgn%.grF_calc_Psi4GFin<-FjpF\qF^qF_qF`qFaqFdqFeqFgqFiqF\rF[pF\pF`rFarF
]p%5Weyl~Scalar,~NP~Psi4GF_pFgoFap%&Psi4_GFdu=F)FVE\[l)FdoF[[lFfoFgoFgn%/grF_ca
lc_CPsi4GFin<)F[sF^vFbsF`vF\tFit-F_bmF\uF[pF\pF]p%2Weyl~Scalar,~Psi4GF_pFgoFapF
`cmF\il=F)FVE\[l*FdoFeflFfo7%F^oF^oF^oFgn%:grF_calc_ClambdabdnbdnbdnGFin<&F[s-F
]r6$Fd[lF^sF_sFbsF[p%-grF_sym_3a13GF`rFarF]p%:pre-Rotation~CoefficientsGF_pFgoF
ap%1lambdabdnbdnbdn_GF]q=F)FVE\[l)FdoF]jlFfoFgoFgn%/grF_calc_NPtauGFinFd]lF[pF\
pF]pF_jlF_pFgoFapF`jl%+ClambdabarG=F)FVE\[l)Fdo%*lambdabarGFfoFgoFgnFhoFin<#F^v
F[pF\pF]p%?NP~Spin~Coefficient,~lambdabarGF_p7#F^vFap%-NPlambdabar_G%'RPhi11G=F
)FVE\[l%FenFcpFgn%0grF_calc_RPhi11GFinFjnF_oF`o%'CPhi22G=F)FVE\[l)FdoF`blFfoFgo
Fgn%0grF_calc_CPhi22GFin<)F[sFbsF`vFerF\tFeyFecmF[pF\pF]pFeblF_pFgoFapFfbl%(Crh
obarG=F)FVE\[l)FdoF[blFfoFgoFgnFhoFin<#FhtF[pF\pF]pF]blF_p7#FhtFapF_blFgq=F)FVE
\[l)FdoFf`lFfoFgoFgnFhoFin<#FhqF[pF\pF]pFh`lF_p7#FhqFapFj`l%'RPhi02G=F)FVE\[l%F
enFbwFgn%0grF_calc_RPhi02GFinFjnF_oF`o%'CPhi11G=F)FVE\[l)FdoFcpFfoFgoFgn%0grF_c
alc_CPhi11GFin<-F[sF^vFgtF_vFhtFjoFbsF`vFerFavFbvF[pF\pF]pFcrF_pFgoFapFdrFct=F)
FVE\[l+FenFctFdoFctFfoFgoFgn%1grF_calc_NPPhi00GFin<.FhpFipF[qF]qF^qF`qFbqF`zF_]
mFgqF[rF\rF[pF\pF`rFarF]pF]uF_pFgoFapF^uFft=F)FVE\[l)FdoFb_mFfoFgoFgn%2grF_calc
_CepsilonGFin<'F[sFhtF\sF_sFbsF[pF\pF]pFd_mF_pFgoFapFe_mFey=F)FVE\[l)FdoFchlFfo
FgoFgn%/grF_calc_CbetaGFin<'F[sFjoF\sF_sFbsF[pF\pF]pFdhlF_pFgoFapFehlFit=F)FVE\
[l)FdoFddlFfoFgoFgn%0grF_calc_CalphaGFin<'F[sF\sF_sFbsFavF[pF\pF]pFfdlF_pFgoFap
FgdlF\t=F)FVE\[l)FdoFgglFfoFgoFgn%0grF_calc_CgammaGFin<'F[sF\sF_sFbsFerF[pF\pF]
pFiglF_pFgoFapFjglFip=F)FVE\[l)FdoFg[lFfoFgoFgn%1grF_calc_NPsigmaGFinFd]lF[pF\p
F]pFi_mF_pFgoFapFj_mF\^m=F)FVE\[l)FdoF\flFfoFgoFgnFhoFinF_flF[pF\pF]p%5Weyl~Sca
lar,~Psi1barGF_pFaflFapFbfl%'CmubarG=F)FVE\[l)FdoF]alFfoFgoFgnFhoFin<#FerF[pF\p
F]pF_alF_p7#FerFapFaal%,CepsilonbarG=F)FVE\[l)FdoF^`lFfoFgoFgnFhoFin<#FftF[pF\p
F]pF``lF_p7#FftFapFb`lFiam=F)FVE\[l*FenFiamFdoFiamFfoFgoFgnFhoFin<#FbclF[pF\pF]
pF[bmF_p7#FbclFapF]bmFh^l=F)FVE\[l)FdoFgdmFfoFgoFgnFhoFin<#FaqF[pF\pF]pFidmF_p7
#FaqFapF[em%&WPsi0G=F)FVE\[l%FenF\]lFgn%/grF_calc_WPsi0GFinF\[lF_oF`[lFi^l=F)FV
E\[l)FdoFaamFfoFgoFgnFhoFin<#FjpF[pF\pF]pFcamF_p7#FjpFapFeamF[q=F)FVE\[l)FdoF]h
lFfoFgoFgn%/grF_calc_NPrhoGFinFd]lF[pF\pF]pF_hlF_pFgoFapF`hlF),
I.grF_when_WPsiRF)F)F)F)@%-%1grF_assignedFlagG6$F[o%%testG%%trueGFVF)F)F)F),
I)DSpinlibRF)F)F)F)C$-%'lprintG6#%NNP~spin~coefficients~via~Debever's~formalism
.G-Fjjm6#%=Last~modified:~March~9,~1995GF)F)F)F),
I3type/interfaceargs-%%listG6#<$%%nameG/Fe[n%)anythingG6",
I(fprintfR6"F[\n6#%^oCopyright~(c)~1994-1998~by~Waterloo~Maple~Inc.~All~rights~
reserved.GF[\n-%&iolibG6$""*9"6#%gnPrints~expressions~to~file~or~pipe~based~on~
a~format~string.GF[\nF[\n%*protectedG,
I2grF_calc_NPLambdaRF$6$%"aGF(F)F)C&>8%,N*&&%+grG_NPtau_G6#F0F>&%*grG_NPpi_GFa]
nF>F>*&&%*grG_NPnu_GFa]nF>&%-grG_NPkappa_GFa]nF>F>*&&%-grG_NPalpha_GFa]nF>&%0gr
G_NPalphabar_GFa]nF>FP*&&%,grG_NPbeta_GFa]nF>&%/grG_NPbetabar_GFa]nF>FP*&&%*grG
_NPmu_GFa]nF>&%+grG_NPrho_GFa]nF>FP*&&%.grG_NPlambda_GFa]nF>&%-grG_NPsigma_GFa]
nF>FP*&Fj]nF>F_^nF>F1*&&%/grG_NPepsilon_GFa]nF>&%0grG_NPgammabar_GFa]nF>FP*&F_^
nF>&%.grG_NPtaubar_GFa]nF>F>*&F_^nF>Fb]nF>F>*&Fj]nF>F_]nF>FP*&Fj]nF>&%-grG_NPpi
bar_GFa]nF>F>*&&%-grG_NPgamma_GFa]nF>F__nF>!"#*&F\`nF>&%2grG_NPepsilonbar_GFa]n
F>FP*&F__nF>Fd^nF>FP*&F__nF>&%-grG_NPmubar_GFa]nF>F>*&F\`nF>Ff^nF>F>*&F\`nF>&%.
grG_NPrhobar_GFa]nF>F>*&F_]nF>Fa^nF>F1*&F_]nF>Fd_nF>F^`n*&Ff^nF>Fd`nF>F^`n*&Ff^
nF>Fa_nF>F1?(F,F>F>(%%NdimGF0Fejm>F\]n,,F\]nF>*&&%,grG_ebdnup_G6%F0F>F,F>-%%dif
fG6$F\`n&%)grG_xup_G6$F0F,F>FP*&&Fean6%F0F1F,F>-Fhan6$,&Ff^nF1F__nFPFjanF>FP*&&
Fean6%F0F?F,F>-Fhan6$Fj]nFjanF>F>*&&Fean6%F0F2F,F>-Fhan6$,&F_]nF1F_^nFPFjanF>F>
>F\]n,$F\]n#F>""'-F46#F\]nF)F)F)F),
I0grF_calc_DCFqdnRF$Fh\nF)F)C%>F\]n""!?(F,F>F>F_anFejm>F\]n,&F\]nF>*&&%/grG_DCF
bupbup_GF_bnF>&%,grG_ebdndn_G6%F0F,%$a1_GF>F>FbcnF)F)F)F),
I0grF_calc_CkappaRF$6'%"iG%"jG%"kG%"lGF(F)F)C%>8(Fhcn?(F,F>F>F_anFejm?(F\]nF>F>
F_anFejm@$0F\]nF,?(8&F>F>F_anFejm@$30FbenF,0FbenF\]n?(8'F>F>F_anFejm@$330FhenF,
0FhenF\]n0FhenFben>F\en,&F\enF>**&%/grG_ebdndnpdn_G6&F0F>F,F\]nF>&F`dn6%F0F?Fbe
nF>&F`dn6%F0F>FhenF>&%3grG_LevCSupupupup_G6'F0F,F\]nFbenFhenF>F>-F46#*&&%*grG_d
etb_GFa]nF>F\enF>F)F)F)F),
I.grF_calc_NPmuRF$F'F)F)C$>F,&F<6&F0F1F2F?F3F)F)F)F),
I0grF_calc_CalphaRF$FednF)F)C&>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en
?(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>*&FifnF>,&*(&Fcfn6
&F0F2F,F\]nF>&F`dn6%F0F1FbenF>FgfnF>F>*(&Fcfn6&F0F1F,F\]nF>&F`dn6%F0F2FbenF>Fgf
nF>FPF>F>>F\en,&F^gnF@Fb]nF@-F46#F\enF)F)F)F),
I(rootDir%-maple/basis/GF),
I/grF_calc_CbetaRF$FednF)F)C&>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en?
(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>*&FifnF>,&*(FbfnF>F
efnF>&F`dn6%F0F1FhenF>F>*(&Fcfn6&F0F?F,F\]nF>&F`dn6%F0F>FbenF>FfjnF>FPF>F>>F\en
,&F^gnF@F_]nF@FbinF)F)F)F),
I0grF_calc_RPhi00RF$F'F)F)C$>F,,$&FI6%F0F>F>F@F3F)F)F)F),
I0grF_calc_RPhi01RF$F'F)F)C$>F,,$&FI6%F0F>F?F@F3F)F)F)F),
I0grF_calc_RPhi02RF$F'F)F)C$>F,,$&FI6%F0F?F?F@F3F)F)F)F),
I)readfileR6#%)filenameGF)F)F)C%-%'printfG6#((%)Reading~G9$%%~...GA((%!GFdinF_]
o-Fj\o6#%(~done.|+GF)F)F)F),
I-PetrovReportRF)6%Fi\n%&ptypeG%&gnameGF)F)C%>FbenF0@'-%)assignedG6#&%,grG_Petr
ov_G6#Fben>F\]nFc^o-Fa^o6#&%.grG_NPPetrov_GFe^o>F\]nFi^o-%&ERRORG6#%IThe~Petrov
~type~has~not~been~calculated.G@%54-Fa^o6#%/grG_reportSizeG/Fe_oFhcn-%&printG6#
%>No~report~has~been~generated.GC*-Fh_o6#((%?The~conclusion~'Petrov~type~=~GF\]
n%"'G-Fh_o6#((%)for~the~GFben%(~metricG-Fh_o6#%Dwas~based~on~the~following~resu
lts:G?(F,F>F>Fe_oFejm-Fh_o6#&%/grG_reportLineGF5-Fh_o6#((%E--->~Therefore~the~m
etric~is~Petrov~GF\]n%".G-Fh_o6#%X---------------------------------------------
----------G-Fh_o6#%YThe~quantities~that~could~not~be~evaluated~to~zero~are:~G?(
F,F>F>%0grG_reportVsizeGFejm-Fh_o6#&%0grG_reportVlineGF5F)F)F)F),
I/grF_calc_NPrhoRF$F'F)F)C$>F,&F<6&F0F?F>F2F3F)F)F)F),
I0grF_calc_CPhi00RF$FednF)F)C&>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en
?(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>**FifnF>&%/grG_DCF
qdnpdn_G6%F0F,F\]nF>F^inF>FgfnF>F>>F\en,(F^gnF@*&Fj]nF>Fg]nF>F1*&F__nF>Ff^nF>F^
`nFbinF)F)F)F),
I0grF_calc_CPhi01RF$FednF)F)C&>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en
?(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>**FifnF>FfcoF>Fefn
F>&F`dn6%F0F2FhenF>F>>F\en,*F^gn#FPF1*&F\`nF>Fg]nF>F1*&F__nF>F_]nF>F^`n&%*grG_P
si1_GFa]nFPFbinF)F)F)F),
I2grF_calc_NPlambdaRF$F'F)F)C$>F,&F<6&F0F1F2F2F3F)F)F)F),
I.grF_calc_Psi0RF$Fh\nF)F)C%>F\]n,&*&F[_nF>,*Ff^nF>Fh`nF>F__nF?F``nFPF>FP*&Fg]n
F>,*F_]nF>Fi_nFPF\^nF>F_^nF?F>F>?(F,F>F>F_anFejm>F\]n,(F\]nF>*&FdanF>-Fhan6$F[_
nFjanF>F>*&FdbnF>-Fhan6$Fg]nFjanF>FPFbcnF)F)F)F),
I0grF_calc_CPhi02RF$FednF)F)C&>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en
?(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>**FifnF>FfcoF>Fihn
F>&F`dn6%F0F?FhenF>F>>F\en,(F^gnF@*&F\`nF>F[_nF>F1*&F_^nF>F_]nF>F^`nFbinF)F)F)F
),
I.grF_calc_Psi1RF$Fh\nF)F)C%>F\]n,**&F_^nF>,&Fh`nF>F``nFPF>FP*&F__nF>,&F\^nF>Fi
_nFPF>F>*&F[_nF>,&Fj]nF>Fb]nF>F>FP*&Fg]nF>,&Fd^nF>F\`nF>F>F>?(F,F>F>F_anFejm>F\
]n,(F\]nF>*&FdanF>-Fhan6$F_^nFjanF>F>*&FdbnF>-Fhan6$F__nFjanF>FPFbcnF)F)F)F),
I.grF_calc_Psi2RF$Fh\nF)F)C&>F\]n,0*&,*F``nF>Ff^nF1Fh`nFPF__nF1F>F\`nF>F>*&,*Fj
]nF^`nFd_nFPFb]nFPFa^nF>F>F_]nF>F>*&,(Fa_nF>Fd^nF>Fd`nFPF>,&Ff^nF>F__nF>F>F>*&,
(F_^nF^`nFi_nFPF\^nF>F>Fj]nF>F>*&,(Fd_nFPFb]nFPFa^nF>F>F_^nF>F>Fd]nF1Fh^nF^`n?(
F,F>F>F_anFejm>F\]n,,F\]nF>FcanF>*&F^bnF>-Fhan6$FajoFjanF>FP*&FibnF>-Fhan6$,&F_
^nF>F_]nF>FjanF>F>FcbnFP>F\]n,$F\]n#F>F?FbcnF)F)F)F),
I.grF_calc_Psi3RF$Fh\nF)F)C%>F\]n,**&Fj]nF>,&Fa_nF>Fd`nFPF>F>*&F\`nF>,&Fa^nF>Fd
_nFPF>F>*&Fe]nF>FajoF>F>*&Fi^nF>F_[pF>FP?(F,F>F>F_anFejm>F\]n,(F\]nF>*&F^bnF>Ff
bnF>FP*&FibnF>FganF>F>FbcnF)F)F)F),
I.grF_calc_Psi4RF$Fh\nF)F)C%>F\]n,&*&Fi^nF>,*Fd^nF>Fd`nF>F\`nF?Fa_nFPF>FP*&Fe]n
F>,*Fb]nF>Fd_nFPFj]nF?Fa^nF>F>F>?(F,F>F>F_anFejm>F\]n,(F\]nF>*&F^bnF>-Fhan6$Fi^
nFjanF>FP*&FibnF>-Fhan6$Fe]nFjanF>F>FbcnF)F)F)F),
I.grF_calc_NPnuRF$F'F)F)C$>F,&F<6&F0F1F2F1F3F)F)F)F),
I7grF_when_CrotbdnbdnbdnRF)F)F)F)@%-%4grF_checkIfAssignedG6#F\ilFejmFVF)F)F)F),
I0grF_calc_RPhi11RF$F'F)F)C$>F,,&FH#F>F2FMFf^pF3F)F)F)F),
I0grF_calc_RPhi12RF$F'F)F)C$>F,,$&FI6%F0F1F?F@F3F)F)F)F),
I0grF_calc_DRicciRF$FednF)F)C&>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en
?(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>*&FifnF>,(*(&%/grG
_DCFrdnpdn_GFhcoF>FefnF>F[eoF>F>*(F^`pF>F[[oF>FfjnF>FP*(FfcoF>F^inF>FfjnF>F1F>F
>>F\en,0F^gnF1F^]nF2Fd]n!"%Fc^nFd`pFh^nF2Ff`n"#;Fg_n!#;-F46#,$F\en#F>"#CF)F)F)F
),
I1grF_calc_NPkappaRF$F'F)F)C$>F,&F<6&F0F?F>F>F3F)F)F)F),
I0grF_calc_DCFpdnRF$Fh\nF)F)C%>F\]nFhcn?(F,F>F>F_anFejm>F\]n,&F\]nF>*&&F^dnFfan
F>F_dnF>F>FbcnF)F)F)F),
I1grF_calc_NPalphaRF$F'F)F)C$>F,,&&F<6&F0F1F>F2F@&F<6&F0F?F2F2F@F3F)F)F)F),
I0grF_calc_CPhi11RF$FednF)F)C&>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en
?(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>*(FifnF>F^`pF>,&*&
FefnF>F[eoF>F>*&F[[oF>FfjnF>F>F>F>>F\en,,F^gn#FPF2F^]nF_eoFd]nF@Fc^nF_eoFh^nF@F
binF)F)F)F),
I0grF_calc_CPhi12RF$FednF)F)C&>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en
?(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>**FifnF>F^`pF>Fihn
F>FjgoF>F>>F\en,(F^gnF@*&F[_nF>Fe]nF>F>*&Fd^nF>F_]nF>FPFbinF)F)F)F),
I2grF_calcConjugateRF$6$%(conjObjG%%rootGF)F)C%>F,&&&%+grG_ObjDefG6#F_]o6#F_p6#
F>>F\]n(%%grG_G&&FdepF56#Fap-F46#-%%conjG6#&F\]nFa]nF)F)F)F),
I7grF_calc_CrotbdnbdnbdnRF$F'6#%boCopyright~(C)~1994-2001~by~Peter~Musgrave,~De
nis~Pollney~and~Kayll~LakeGF)C$>F,,(&%6grG_Clambdabdnbdnbdn_G6&F0Fbdn%$a2_G%$a3
_GF@&F\gp6&F0F_gpFbdnF^gpF@&F\gp6&F0F^gpF_gpFbdnF_eoF3F)F)F)F),
I'DcurveRF)F)F)F)C$-Fjjm6#%PCurvature~coefficients~via~Debever's~formalism.GF][
nF)F)F)F),
I0grF_calc_RPhi22RF$F'F)F)C$>F,,$&FI6%F0F1F1F@F3F)F)F)F),
I1grF_calc_NPPhi00RF$Fh\nF)F)C%>F\]n,**&Ff^nF>,(Ff^nF>F__nF>F``nF>F>FP*&F[_nF>&
%0grG_NPsigmabar_GFa]nF>FP*&&%0grG_NPkappabar_GFa]nF>F_]nF>F>*&Fg]nF>,(Fj]nF?Fa
^nF>Fb]nFPF>F>?(F,F>F>F_anFejm>F\]n,(F\]nF>*&FdanF>-Fhan6$Ff^nFjanF>F>*&FibnF>F
jfoF>FPFbcnF)F)F)F),
I1grF_calc_NPPhi01RF$Fh\nF)F)C%>F\]n,.*&F\^nF>,(Fh`nF>F__nF>F``nF^`nF>FP*&F``nF
>,&F_^nF>Fi_nFPF>F>*&Fa^nF>F[_nF>FP*&F\ipF>&%1grG_NPlambdabar_GFa]nF>F>*&Fg]nF>
Fa_nF>F>*&Fi_nF>Fh`nF>FP?(F,F>F>F_anFejm>F\]n,(F\]nF>*&FdanF>-Fhan6$F\^nFjanF>F
>*&FdbnF>-Fhan6$F``nFjanF>FPFbcnF)F)F)F),
I0grF_calc_PetrovRF$Fh\nF)F)C$>F\]n-%)grpetrovG6'&%*grG_Psi0_GFa]nFbeo&%*grG_Ps
i2_GFa]n&%*grG_Psi3_GFa]n&%*grG_Psi4_GFa]nFbcnF)F)F)F),
I1grF_calc_NPPhi02RF$Fh\nF)F)C%>F\]n,**&FbjpF>,(F``nF?F__nFPFh`nFPF>F>*&Fi_nF>,
(Fi_nF>F\^nF>F_^nFPF>FP*&F[_nF>Fd`nF>FP*&&%-grG_NPnubar_GFa]nF>Fg]nF>F>?(F,F>F>
F_anFejm>F\]n,(F\]nF>*&FdanF>-Fhan6$FbjpFjanF>F>*&FdbnF>-Fhan6$Fi_nFjanF>FPFbcn
F)F)F)F),
I.grF_when_RPhiRF)F)F)F)@%FajmFejmFVF)F)F)F),
I*interfaceR6"6&%"rG%"vG%#naG%#vaG6#%]oCopyright~(c)~1999~by~the~Waterloo~Maple
~Inc.~All~rights~reserved.GFi]qC&@$4-%%typeG6$7#9".%.interfaceargsGYQ2invalid~a
rgumentsFi]q>8$%%NULLG?&8%Fg^qFejm@%-Fe^q6$Fa_qFe[n@'/Fa_q.%+patchlevelGC$>8'-F
h_qFi]q@%/F[`q-Fg_qFi]q>F^_q6$F^_qFhcn>F^_q6$F^_qF[`q/Fa_q.%+autoassignG>F^_q6$
F^_q%5interface/autoassignG>F^_q6$F^_q-%+streamcallG6#-%.INTERFACE_GETG6#Fa_qC%
>8&-%#opG6$F>Fa_q>F[`q-Ffaq6$F1Fa_q@'/FdaqFg_qY6$Q1%1~cannot~be~setFi]qFdaq/Fda
qFe`qC$@$4-Fe^q6$F[`q%'symbolGYQAautoassign~root~must~be~a~symbolFi]q@'-%'membe
rG6$F[`q<$FV.%%noneG-%'assignG6#/.Fi`qF_cq/F[`qFejm-Facq6#/Fdcq.F\o-Facq6#/Fdcq
F[`q-F]aq6#-%.INTERFACE_SETG6$FdaqF[`qOF^_qFi]q6#Fh_qFi]qFe\n,
I.grF_calc_CtauRF$FednF)F)C%>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en?(
FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>*&FifnF>,(*(FbfnF>Fi
hnF>FjgoF>F>*(F\inF>F[[oF>FjgoF>FP*(FijnF>F^inF>FjgoF>FPF>F>-F46#,$F^gnF@F)F)F)
F),
I0grF_calc_CPhi22RF$FednF)F)C&>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en
?(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>**FifnF>&%/grG_DCF
pdnpdn_GFhcoF>FihnF>FjgoF>F>>F\en,(F^gnF@*&Fe]nF>F_^nF>F1*&Fd^nF>F\`nF>F^`nFbin
F)F)F)F),
I.grF_calc_NPpiRF$F'F)F)C$>F,&F<6&F0F1F2F>F3F)F)F)F),
I)grpetrovRF)6@Ffdn%%maskG%$PsiGF[^o%#f1G%#f2G%#f3G%#t1G%#t2G%#t3G%#t4G%"AG%"DG
%"EG%"FG%"GG%"HG%"IG%"JG%"QG%"SG%"UG%"VG%"WG%"ZG%$strG%%str1G%%str2G%%str3G%%st
r4GF)F)C*>Fe_oFhcn>F]boFhcn>Fben-%&arrayG6#;FhcnF2?(F,FhcnF>F2Fejm>&FbenF5&9"6#
,&F,F>F>F>>F\]nFhcn?(F,FhcnF>F2FejmC%>8=(%0Weyl~scalar~PsiGF,-%+grF_reportG6%Fd
]oFejqF\jq@$0F\jqFhcn>F\]n,&F\]nF>)F1,&F2F>F,FPF>@[o/F\]nFhcn>Fhen%"OG/F\]nF>>F
hen%/N~(or~simpler)G/F\]nF1>Fhen%1III~(or~simpler)G/F\]nF?>FhenFj[r/F\]nF2>Fhen
%/D~(or~simpler)G/F\]n""&>Fhen%0II~(or~simpler)G/F\]nFacn>FhenFc\r/F\]n""(C&>Fe
jq%;2*Psi[3]^2-3*Psi[2]*Psi[4]G>85-%.grF_pSimplifyG6#,&*$&Fben6#F?F1F1*&&Fben6#
F1F>&Fben6#F2F>!"$@%/F\]rFhcn>FhenF_\r>FhenFc\r-Fijq6%Fd]oFejqF\]r/F\]n"")>Fhen
Fj[r/F\]nFa\n>Fhen%/I~(or~simpler)G/F\]n"#5>FhenFe^r/F\]n"#6C&>Fejq%A27*Psi[1]*
Psi[4]^2~+~64*Psi[3]^3G>F\]r-F^]r6#,&*&&FbenFgepF>Fg]rF1"#F*$Fb]rF?"#k@%F[^r>Fh
enFc\r>FhenFe^rF^^r/F\]nFL>FhenFc\r/F\]n"#8C&>Fejq%=Psi[1]^2*Psi[4]~+~2*Psi[2]^
3G>F\]r-F^]r6#,&*&Fc_rF1Fg]rF>F>*$Fe]rF?F1@%F[^r>FhenFc\r>FhenFe^rF^^r/F\]n"#9C
&>Fejq%<9*Psi[2]^2-16*Psi[1]*Psi[3]G>F\]r-F^]r6#,&*$Fe]rF1Fa\n*&Fc_rF>Fb]rF>Ff`
p@%F[^r>FhenFc\r>FhenFe^rF^^r/F\]n"#:C)>8>%=3*Psi[2]^2~-~4*Psi[1]*Psi[3]G>8?%B2
*Psi[2]*Psi[3]~-~3*Psi[1]*Psi[4]G>F\]r-F^]r6#,&FcarF?FdarFd`p>F\en-F^]r6#,&*&Fe
]rF>Fb]rF>F1*&Fc_rF>Fg]rF>Fi]r-Fijq6%Fd]oF\brF\]r-Fijq6%Fd]oF_brF\en@%F[^r@%/F\
enFhcn>FhenFj[r>FhenFe^r@%Facr>FhenFe^rC&>8@%=9*Psi[2]*Psi[4]~-~8*Psi[3]^2G>8)-
F^]r6#,&Fd]rFa\nFa]r!")-Fijq6%Fd]oFhcrF[dr@%/F[drFhcn>FhenFe^rC&>8A%03*f1^2~+~2
*I*f2G>8*-F^]r6#,&*$F\enF1F?*&F\]rF>F[drF>F1-Fijq6%Fd]oFgdrFjdr@%/FjdrFhcn>Fhen
Fc\r>FhenFe^r/F\]nFe`p>FhenFg[r/F\]n"#<>FhenFe^r/F\]n"#=>FhenFe^r/F\]n"#>C&>Fej
q%>Psi[0]*Psi[4]^3~-~27*Psi[3]^4G>F\]r-F^]r6#,&*&&Fben6#FhcnF>Fg]rF?F>*$Fb]rF2!
#FF^^r@%F[^r>FhenFc\r>FhenFe^r/F\]n"#?>FhenFc\r/F\]n"#@C&>Fejq%;9*Psi[2]^2~-~Ps
i[0]*Psi[4]G>F\]r-F^]r6#,&FcarFa\n*&FhfrF>Fg]rF>FPF^^r@%F[^r>FhenF_\r>FhenFe^r/
F\]n"#AC&>Fejq%=Psi[0]*Psi[4]^2~+~2*Psi[2]^3G>F\]r-F^]r6#,&*&FhfrF>Fg]rF1F>Ff`r
F1F^^r@%F[^r>FhenFc\r>FhenFe^r/F\]n"#BC)>F\br%;Psi[0]*Psi[4]~+~3*Psi[2]^2G>F_br
%=4*Psi[2]*Psi[4]~-~3*Psi[3]^2G>F\]r-F^]r6#,&F[hrF>FcarF?>86-F^]r6#,&Fd]rF2Fa]r
Fi]r-Fijq6%%#~IGF\brF\]r-Fijq6%%#~JGF_brFhir@%F[^r@%/FhirFhcn>FhenFj[r>FhenFe^r
@%Fdjr>FhenFe^rC&>Fhcr%6Psi[0]*J~-~2*Psi[2]*IG>Fjdr-F^]r6#,&*&FhfrF>FhirF>F>*&F
e]rF>F\]rF>F^`n-Fijq6%%$~f3GFhcrFjdr@%Fcer>FhenFe^rC&>Fgdr%4Psi[4]*I^2~-~3*J*f3
G>80-F^]r6#,&*&Fg]rF>F\]rF1F>*&FhirF>FjdrF>Fi]r-Fijq6%%#~DGFgdrF[\s@%/F[\sFhcn>
FhenFc\r>FhenFe^r/F\]nF[ap>FhenFj[r/F\]n"#DC&>Fejq%>Psi[4]*Psi[0]^3~-~27*Psi[1]
^4G>F\]r-F^]r6#,&*&Fg]rF>FhfrF?F>*$Fc_rF2F[grF^^r@%F[^r>FhenFc\r>FhenFe^r/F\]n"
#EC&>Fejq%A27*Psi[3]*Psi[0]^2~+~64*Psi[1]^3G>F\]r-F^]r6#,&*&Fb]rF>FhfrF1Fd_r*$F
c_rF?Ff_rF^^r@%F[^r>FhenFc\r>FhenFe^r/F\]nFd_rC*>8+-F^]r6#F[hr>8,-F^]r6#Fdar>8-
-F^]r6#*&FhfrF>Fb]rF1>8.-F^]r6#Fe`r>Fejq%CPsi[0]*Psi[3]^2~-~~Psi[4]*Psi[1]^2G>8
:-F^]r6#,&Fa_sF>Ff_sFP-Fijq6%%#~VGFejqF\`s@%/F\`sFhcnC&>Fejq%@Psi[0]*Psi[4]~+~2
*Psi[1]*Psi[3]G>89-F^]r6#,&Fi^sF>F]_sF1-Fijq6%%#~UGFejqFi`s@%/Fi`sFhcn>FhenF_\r
C&>Fejq%APsi[0]*Psi[4]~-~16*Psi[1]*Psi[3]G>8;-F^]r6#,&Fi^sF>F]_sFf`p-Fijq6%%#~W
GFejqFgas@%/FgasFhcn>FhenFc\r>FhenFe^rC)>Fejq%@Psi[0]*Psi[4]~-~4*Psi[1]*Psi[3]G
>F\]r-F^]r6#,&Fi^sF>F]_sFd`p-Fijq6%F^jrFejqF\]r>Fejq%C-Psi[0]*Psi[3]^2~-~Psi[4]
*Psi[1]^2G>Fhir-F^]r6#,&Fa_sFPFf_sFP-Fijq6%FajrFejqFhir@%F[^r@%Fdjr>FhenFj[r>Fh
enFe^r@%Fdjr>FhenFe^rC&>Fejq%-I^3~-~27*J^2G>F[\s-F^]r6#,&*$F\]rF?F>*$FhirF1F[gr
-Fijq6%Fc\sFejqF[\s@%Fe\s>FhenFc\r>FhenFe^r/F\]n"#GC&>Fejq%=2*Psi[1]^2~-~3*Psi[
2]*Psi[0]G>F\]r-F^]r6#,&*$Fc_rF1F1*&Fe]rF>FhfrF>Fi]rF^^r@%F[^r>FhenF_\r>FhenFc\
r/F\]n"#HC)>Fejq%;Psi[4]*Psi[0]~+~3*Psi[2]^2G>F\]rFdirFibs>Fejq%=4*Psi[2]*Psi[0
]~-~3*Psi[1]^2G>Fhir-F^]r6#,&FaesF2F`esFi]rFacs@%F[^r@%Fdjr>FhenFj[r>FhenFe^r@%
Fdjr>FhenFe^rC&>Fejq%6Psi[4]*J~-~2*Psi[2]*IG>Fjdr-F^]r6#,&*&Fg]rF>FhirF>F>Fa[sF
^`n-Fijq6%Fd[sFejqFjdr@%Fcer>FhenFe^rC&>Fejq%4Psi[0]*I^2~-~3*J*f3G>F[\s-F^]r6#,
&*&FhfrF>F\]rF1F>F`\sFi]rFbds@%Fe\s>FhenFc\r>FhenFe^r/F\]n"#IC)>FejqF]br>F\]rFb
brFibs>Fejq%B2*Psi[2]*Psi[1]~-~3*Psi[3]*Psi[0]G>F\en-F^]r6#,&*&Fe]rF>Fc_rF>F1*&
Fb]rF>FhfrF>Fi]r-Fijq6%%$~f1GFejqF\en@%F[^r@%Facr>FhenFj[r>FhenFe^r@%Facr>FhenF
e^rC&>Fejq%=9*Psi[2]*Psi[0]~-~8*Psi[1]^2G>F[dr-F^]r6#,&FaesFa\nF`esF_dr-Fijq6%%
$~f2GFejqF[dr@%Fcdr>FhenFe^rC&>FejqFhdr>FhirF[er-Fijq6%Fd]oFejqFhir@%Fdjr>FhenF
c\r>FhenFe^rC,>F\br%9Psi[0]*Psi[2]~-~Psi[1]^2G>F_br%9Psi[0]*Psi[4]~-~Psi[2]^2G>
Fhcr%>Psi[0]*Psi[3]~-~Psi[1]*Psi[2]G>84-F^]r6#,&FaesF>F`esFP>81-F^]r6#,&F[hrF>F
carFP>82-F^]r6#,&FjhsF>FihsFP-Fijq6%%#~HGF\brF`[t-Fijq6%%#~EGF_brFe[t-Fijq6%%#~
FGFhcrFj[t@%/F`[tFhcn@%/Fj[tFhcn@%/Fe[tFhcn>FhenFg[r>FhenFe^r@%F\]tC&>Fejq%=37*
Psi[2]^2+27*Psi[1]*Psi[3]G>87-F^]r6#,&Fcar"#PFdarFd_r-Fijq6%%#~QGFejqFd]t@%/Fd]
tFhcn>FhenFc\r>FhenFe^rC'>Fejq%AE~-~4*(Psi[1]*Psi[3]~-~Psi[2]^2)G>8/-F^]r6#,&Fd
arF>FcarFP>F\]r-F^]r6#,&Fe[tF>Fd^tFd`pFibs@%F[^r>FhenFe^rC)>Fejq%MPsi[2]*(Psi[1
]*Psi[3]~-~Psi[2]^2)~-~Psi[3]*FG>Fhir-F^]r6#,&*&Fe]rF>Fd^tF>F>*&Fb]rF>Fj[tF>FPF
acs>FejqF[ds>F[\sF]dsFbds@%Fe\s>FhenFc\r>FhenFe^rC)>Fejq%9Psi[1]*Psi[3]~-~Psi[2
]^2G>Fd^tFe^t-Fijq6%%#~AGFejqFd^t>Fejq%(E~-~4*AG>F\]rFi^tFibs@%F[^rC&>Fejq%?Psi
[2]*A~-~Psi[3]*F~+~Psi[4]*HG>Fhir-F^]r6#,(Fe_tF>Ff_tFP*&Fg]rF>F`[tF>F>Facs@%Fdj
r>FhenFj[r>FhenFe^rC&>Fejq%6Psi[0]*F~-~2*Psi[1]*HG>83-F^]r6#,&*&FhfrF>Fj[tF>F>*
&Fc_rF>F`[tF>F^`n-Fijq6%%#~GGFejqFfat@%/FfatFhcnC&>Fejq%4Psi[0]^2*I~-~12*H^2G>8
<-F^]r6#,&*&FhfrF1F\]rF>F>*$F`[tF1!#7-Fijq6%%#~ZGFejqFebt@%/FebtFhcn>FhenF_\rC&
>Fejq%3Psi[0]^2*I~-~3*H^2G>88-F^]r6#,&FibtF>FjbtFi]r-Fijq6%%#~SGFejqFfct@%/Ffct
Fhcn>FhenFc\r>FhenFe^rC&>FejqFi`t>FhirF[atFacs@%Fdjr>FhenFe^rC&>FejqF[ds>F[\sF]
dsFbds@%Fe\s>FhenFc\r>FhenFe^r-F46#FhenF)6&F_aoFe_oFaboF]boF)F),
I:grF_when_ClambdabdnbdnbdnRF)F)F)F)@%-F_^p6#F\sFejmFVF)F)F)F),
I-grF_calc_CmuRF$FednF)F)C%>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en?(F
benF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>*&FifnF>,(*(F\inF>F[[
oF>FfjnF>F>*(FijnF>F^inF>FfjnF>F>*(FghnF>FefnF>FfjnF>FPF>F>-F46#,$F^gnF_eoF)F)F
)F),
I1grF_calc_NPPhi11RF$Fh\nF)F)C&>F\]n,6*&Fb]nF>F_[pF>FP*&Ff^nF>F\ioF>FP*&Fj]nF>,
*Fi_nFPF_]nFPF\^nFPF_^nF1F>F>*&F__nF>,*Fa_nF>Fd`nF>F\`nF1Fd^nFPF>F>Fg`nF>Fc_nFP
F_`nF>F^^nFPFh^nF>Fd]nF>?(F,F>F>F_anFejm>F\]n,,F\]nF>FcanF>*&F^bnF>FdioF>FPFcbn
F>*&FibnF>FaioF>FP>F\]n,$F\]nF@FbcnF)F)F)F),
I1grF_calc_NPPhi12RF$Fh\nF)F)C%>F\]n,.*&F\`nF>,(F_]nF>F\^nFPF_^nFPF>FP*&F_^nF>,
(F\`nF>Fa_nFPFd^nFPF>F>FidpFP*&Fj]nF>FbjpF>FPFhdpF>*&F__nF>Fi\qF>F>?(F,F>F>F_an
Fejm>F\]n,(F\]nF>*&FdbnF>FganF>F>*&F^bnF>FaioF>FPFbcnF)F)F)F),
I/grF_calc_CPsi0RF$FednF)F)C&>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en?
(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>**FifnF>FfcoF>F[[oF
>FjgoF>F>>F\en,(F^gnF@*&F_^nF>Fg]nF>F1*&F__nF>F[_nF>F^`nFbinF)F)F)F),
I0grF_calc_CsigmaRF$FednF)F)C%>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en
?(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>**FijnF>F[[oF>Fjgo
F>FifnF>F>-F46#,$F^gnFPF)F)F)F),
I/grF_calc_CPsi1RF$FednF)F)C&>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en?
(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>**FifnF>F^`pF>F[[oF
>FjgoF>F>>F\en,(F^gnF@*&Fb]nF>F[_nF>FP*&Fg]nF>Fd^nF>F>FbinF)F)F)F),
I/grF_calc_CPsi2RF$FednF)F)C&>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en?
(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>*&FifnF>,(F``pF>F]`
pFPFa`pF>F>F>>F\en,0F^gnF`cnFc^nFb[pFh^n#FPF?F^]nFa]uFd]nFb[pFf`n#F1F?Fg_n#F^`n
F?FbinF)F)F)F),
I/grF_calc_CPsi3RF$FednF)F)C&>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en?
(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>**FifnF>F^`pF>F^inF
>FfjnF>F>>F\en,(F^gnF@*&Fi^nF>F_]nF>FP*&Fe]nF>Ff^nF>F>FbinF)F)F)F),
I/grF_calc_CPsi4RF$FednF)F)C&>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en?
(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>**FifnF>FgfqF>F^inF
>FfjnF>F>>F\en,(F^gnF@*&Fj]nF>Fe]nF>F1*&F\`nF>Fi^nF>F^`nFbinF)F)F)F),
I'printfR6"Fj_u6#F]\nFj_uC%-Fi[n6$%(defaultG9"-%'fflushG6#F_`uF__q6#%]oPrints~e
xpressions~to~the~default~output~based~on~a~format~string.GFj_uFj_uFe\n,
I.grF_calc_detbR6#F%6&Fi\n%"bGF_hq%#fnGFffpF)C'@+-F_^p6$F\rFV>FhenFean-F_^p6$F\
dmFV>Fhen%,grG_ebupdn_G-F_^p6$F\sFVC$-%)grF_coreG6$F\dmFejm>FhenFdau-F_^p6$-F]r
6$Fd[lF_rFVC$-Fiau6$F\rFejm>FhenFean-F]_o6#%enA~basis~must~be~defined~in~order~
to~calculate~this~object.G>Fben-&%'linalgG6#%'matrixG6$F_anF_an?(F,F>F>F_anFejm
?(F\]nF>F>F_anFejm>&Fben6$F,F\]n&FhenFhco>F_gn-&Fjbu6#%$detGFe^o@$/FhenFdau>F_g
n*$F_gnFPF)6#F`gnF)F),
I:grF_calc_ClambdabdnbdnbdnR6$F%Fb[n6)Fi\nFj`u%"cG%"dGF]r%"fGF(F)F)C%>FjdrFhcn?
(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en?(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFe
jm@$Fjen?(F\enF>F>F_anFejm@$30F\enFbdn0F\enF_gp?(F[drF>F>F_anFejm@$330F[drF\en0
F[drFbdn0F[drF_gp>Fjdr,&FjdrF>*,&Fcfn6&F0F^gpF,F\]nF>FifnF>&Fjfn6'F0FbdnF_gpF\e
nF[drF>&Fdau6%F0F\enFbenF>&Fdau6%F0F[drFhenF>F>-F46#,$*&FjdrF>F_gnF>F@F)F)F)F),
I2grF_calc_CepsilonRF$FednF)F)C&>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`
en?(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>*&FifnF>,&*(Fbfn
F>FefnF>F[eoF>F>*(FijnF>F[[oF>F[eoF>FPF>F>>F\en,&F^gnF@Ff^nF@FbinF)F)F)F),
I)basislibRF)F)F)F)C$-Fjjm6#%HBasis/tetrad~related~object~definitionsG-Fjjm6#%>
Last~modified~23~January~2001GF)F)F)F),
I-grF_calc_CnuRF$FednF)F)C%>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en?(F
benF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>**F\inF>F^inF>FfjnF>F
ifnF>F>F[[uF)F)F)F),
I1grF_calc_NPPhi22RF$Fh\nF)F)C%>F\]n,**&Fe]nF>,(F_]nF>F_^nFi]rF\^nFPF>FP*&Fd^nF
>,(Fd^nF>F\`nF>Fa_nF>F>FP*&Fi^nF>FbjpF>FP*&Fi\qF>Fb]nF>F>?(F,F>F>F_anFejm>F\]n,
(F\]nF>*&FdbnF>Fc]pF>F>*&F^bnF>-Fhan6$Fd^nFjanF>FPFbcnF)F)F)F),
I1grF_calc_ClambdaRF$FednF)F)C%>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`e
n?(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>**FghnF>FihnF>F[e
oF>FifnF>F>F\gnF)F)F)F),
I-grF_calc_DCFRF$F'F)F)C$>F,&F^dn6%F0FbdnF^gpF3F)F)F)F),
I0grF_calc_CgammaRF$FednF)F)C&>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en
?(FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>*&FifnF>,&*(FghnF>
FihnF>FjgoF>F>*(F\inF>F^inF>FjgoF>FPF>F>>F\en,&F^gnF@Fd^nF@FbinF)F)F)F),
I/grF_calc_NPtauRF$F'F)F)C$>F,&F<6&F0F?F>F1F3F)F)F)F),
I1grF_calc_NPsigmaRF$F'F)F)C$>F,&F<6&F0F?F>F?F3F)F)F)F),
I3grF_calc_NPepsilonRF$F'F)F)C$>F,,&&F<6&F0F1F>F>F@&F<6&F0F?F2F>F@F3F)F)F)F),
I.grF_calc_CrhoRF$FednF)F)C%>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en?(
FbenF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>*&FifnF>,(*(FbfnF>Fi
hnF>FgfnF>F>*(FijnF>F^inF>FgfnF>FP*(FghnF>FefnF>FgfnF>F>F>F>FfeqF)F)F)F),
I+grF_reportR6%%&vnameGF]iq%&valueGF)F)F)@%/9&FhcnC$>Fe_o,&Fe_oF>F>F>@%0F_]oFd]
o>&F_aoFd_o/F_]o(9%%%~=~0G>Fa`v/Fd`vFhcnC&>Fe_oF]`v>F]bo,&F]boF>F>F>@%F_`v>Fa`v
/F_]o(Fd`v%A~could~not~be~evaluated~to~zero.G>Fa`v((Fd]oFd`vF`av@%F_`v>&Fabo6#F
]bo/F_]oFj_v>Ffav/Fd`vFj_vF)F^etF)F),
I'fflushR6"F]bv6#F]\nF]bv-F_\n6$F]ir9"6#%QFlushes~any~unwritten~data~to~the~phy
sical~file.GF]bvF]bvFe\n,
I0grF_calc_DCFrdnRF$Fh\nF)F)C%>F\]nFhcn?(F,F>F>F_anFejm>F\]n,&F\]nF>*&&F^dnFebn
F>F_dnF>F>FbcnF)F)F)F),
I0grF_precalc_DCFRFh`u6#Fi\nF)F)C0>&F^dnFe[o,$Fe]nF^`n>&F^dn6%F0F1F>,$F_]nF^`n>
&F^dn6%F0F?F>,$F\`nF^`n>&F^dnF\\o,$Fi^nF1>&F^dnF]_p,$Ff^nF1>&F^dnFc\o,$Fj]nF1>&
F^dn6%F0F>F2,$Fd^nF1>&F^dn6%F0F1F2,$F[_nF1>&F^dnFN,$F_^nF1>&F^dnFJ,$Fb]nF^`n>&F
^dnF`hp,$Fg]nF^`n>&F^dn6%F0F?F1,$F__nF^`n?(F,F>F>F2Fejm>&F^dnFjbnFhcn-Fbjm6$Fa[
l%$setGF)6#F^dnF)F),
I-grF_calc_CpiRF$FednF)F)C%>F\enFhcn?(F,F>F>F_anFejm?(F\]nF>F>F_anFejm@$F`en?(F
benF>F>F_anFejm@$Fden?(FhenF>F>F_anFejm@$Fjen>F\en,&F\enF>*&FifnF>,(*(FbfnF>Fih
nF>F[eoF>F>*(F\inF>F[[oF>F[eoF>FP*(FghnF>FefnF>F[eoF>F>F>F>FfeqF)F)F)F),
I.grF_pSimplifyR6#%%exprGF)F)F)-%,grG_simpHowG6%%+grG_preSeqGF_]o%,grG_postSeqG
F)6%FhgvFjgvF[hvF)F),
I1grF_calc_NPgammaRF$F'F)F)C$>F,,&&F<6&F0F1F>F1F@&F<6&F0F?F2F1F@F3F)F)F)F),
I/grF_calc_WPsi0RF$F'F)F)C$>F,&F.6'F0F>F?F>F?F3F)F)F)F),
I/grF_calc_WPsi1RF$F'F)F)C$>F,&F.6'F0F>F1F>F?F3F)F)F)F),
I/grF_calc_WPsi2RF$F'F)F)C$>F,&F.6'F0F>F?F2F1F3F)F)F)F),
I/grF_calc_WPsi3RF$F'F)F)C$>F,&F.6'F0F>F1F2F1F3F)F)F)F)
