M6R0
I0grF_sym_D3MRiemR6%%+objectNameG%%rootG%'calcFnG6$%"NG%%dSeqG6#%boCopyright~(C
)~1994-2001~by~Peter~Musgrave,~Denis~Pollney~and~Kayll~LakeG6"C&>8$&%%NdimG6#%/
grG_metricNameG@$3%)grG_calcG-%)assignedG6#9&?(%$a1_G"""F>F0%%trueG?(%$a2_GF>F>
F0F??(%$a3_GF>F>F0F??(%$a5_GF>F>F0F??(%$a6_GF>F>F0F??(%$a7_GF>F>F0F?C$>&(%%grG_
G9%6+F4%-grG_operandsGF=F=FAFCFEFGFI""!>&FM6+F4FQF=FAFCFCFEFGFIFR?(F=F>F>,&F0F>
!""F>F??(FA,&F=F>F>F>F>F0F??(FCF>F>FWF??(%$a4_G,&FCF>F>F>F>F0F??(FEF>F>F0F??(FG
F>F>F0F??(FIF>F>F0F?C$@$F6C&>&FM6+F4FQF=FAFgnFCFEFGFI,$&FM6+F4FQF=FAFCFgnFEFGFI
FX>&FM6+F4FQFAF=FCFgnFEFGFIFbo>&FM6+F4FQFAF=FgnFCFEFGFIFco>Fco-F;6$9$7)F=FAFCFg
nFEFGFI-%,grF_symCoreG6%F^pF_pFO%%NULLGF-6,F=FAFCFgnFEFGFI%$a8_G%$a9_G%%a10_GF-
F-,
I0grF_calc_d2RiemR6$%'objectG%&iListG6-%"aG%"bG%"cG%"dG%#e1G%#e2G%#f1G%#f2G%"sG
F)F&F-F-C'>8.%5grG_Rdndnupupcdncdn_G>8-F1>8,FR?(8(F>F>F\rF??(8)F>F>F\rF?@$0&%+g
rG_gupup_G6%F4F`rFbrFR?(8*F>F>F\rF??(8+F>F>F\rF?@$0&Ffr6%F4FirF[sFR?(F0F>F>F\rF
??(8%,&F0F>F>F>F>F\rF??(8&F>F>F\rF??(8',&FesF>F>F>F>F\rF?>F^r,&F^rF>**FerF>F^sF
>&Fiq6)F4F0FbsFesFgsF`rFirF>&Fiq6)F4FesFgsF0FbsFbrF[sF>F>-%'RETURNG6#,$F^r""%F-
F-F-F-,
I+grG_newObj=F-%&falseGE\[l-%$d4RG=F-FgtE\[l(%,grC_dependsG<$-%"gG6$%#upGFau-%,
RicciscalarG6&%$cdnGFeuFeuFeu%.grC_indexListG7"%+grC_headerG%%~d4RG%)grC_rootG%
)d4Ricci_G%,grC_rootStrG%%d4R~G%-grC_symmetryG%/grF_sym_scalarG%+grC_calcFnG%-g
rF_calc_d4RG%+diWeylstarG=F-FgtE\[l)F\u<#-%&CstarG6'%#dnGFivFauFauFeuFfuFguFhu%
A~C_|fra~b~c~d~;~e|hr~C^|fra~b~c~d~;~e|hrGFju%,diWeylstar_GF\v%,diWeylstar~GF^v
F_v%0grC_calcFnParmsG%6grG_Cstardndnupupcdn_GF`v%0grF_calc_diRiemG%$diSG=F-FgtE
\[l)F\u<#-%"SG6%FivFauFeuFfuFguFhu%9~S_|fra~b~;~e|hr~S^|fra~b~;~e|hrGFju%%diS_G
F\v%%diS~GF^vF_vF]w%.grG_Sdnupcdn_GF`v%1grF_calc_diRicciG%$d2RG=F-FgtE\[l(F\u<$
F^u-Fcu6$FeuFeuFfuFguFhu%%~d2RGFju%)d2Ricci_GF\v%%d2R~GF^vF_vF`v%-grF_calc_d2RG
%'diRiemG=F-FgtE\[l)F\u<#-%"RGFhvFfuFguFhu%A~R_|fra~b~c~d~;~e|hr~R^|fra~b~c~d~;
~e|hrGFju%(diRiem_GF\v%(diRiem~GF^vF_vF]w%2grG_Rdndnupupcdn_GF`vF_w%#dRG=F-FgtE
\[l(F\u<$-Fcu6#FeuF^uFfuFguFhu%$~dRGFju%(dRicci_GF\v%$dR~GF^vF_vF`v%,grF_calc_d
RG%'diWeylG=F-FgtE\[l)F\u<#-%"CGFhvFfuFguFhuFjvFju%(diWeyl_GF\v%(diWeyl~GF^vF_v
F]w%2grG_Cdndnupupcdn_GF`vF_w%'d3RiemG=F-FgtE\[l(F\u<$F^u-F[y6)FivFivFauFauFeuF
euFeuFfuFguFhu%(~d3RiemGFju%(d3Riem_GF\v%(d3Riem~GF^vF_vF`v%0grF_calc_d3RiemG%(
diRicciG=F-FgtE\[l)F\u<#-F[yFfwFfuFguFhu%9~R_|fra~b~;~e|hr~R^|fra~b~;~e|hrGFju%
)diRicci_GF\v%)diRicci~GF^vF_vF]w%.grG_Rdnupcdn_GF`vF[x%$d3RG=F-FgtE\[l(F\u<$F^
u-Fcu6%FeuFeuFeuFfuFguFhu%%~d3RGFju%)d3Ricci_GF\v%%d3R~GF^vF_vF`v%-grF_calc_d3R
G%'d4RiemG=F-FgtE\[l(F\u<$F^u-F[y6*FivFivFauFauFeuFeuFeuFeuFfuFguFhu%(~d4RiemGF
ju%(d4Riem_GF\v%(d4Riem~GF^vF_vF`v%0grF_calc_d4RiemG%'d2RiemG=F-FgtE\[l(F\u<$F^
u-F[y6(FivFivFauFauFeuFeuFfuFguFhu%(~d2RiemGFju%(d2Riem_GF\v%(d2Riem~GF^vF_vF`v
FhpF-,
I3type/interfaceargs-%%listG6#<$%%nameG/Fh]l%)anythingG6",
I(fprintfR6"F^^l6#%^oCopyright~(c)~1994-1998~by~Waterloo~Maple~Inc.~All~rights~
reserved.GF^^l-%&iolibG6$""*9"6#%gnPrints~expressions~to~file~or~pipe~based~on~
a~format~string.GF^^lF^^l%*protectedG,
I-grF_calc_d2RRFjp6)FbqFcqFdqFeqFfqF)F&F-F-C'>Fir%7grG_Ricciscalarcdncdn_G>FbrF
1>F`rFR?(F0F>F>FbrF??(FbsF>F>FbrF?@$0&Ffr6%F4F0FbsFR?(FesF>F>FbrF??(FgsF>F>FbrF
?@$0&Ffr6%F4FesFgsFR>F`r,&F`rF>**Fe_lF>F[`lF>&Fir6%F4F0FesF>&Fir6%F4FbsFgsF>F>-
Fat6#F`rF-F-F-F-,
I(rootDir%.maple/dinvar/GF-,
I0grF_sym_D4MRiemRF$F(F+F-C&>F0F1@$F6?(F=F>F>F0F??(FAF>F>F0F??(FCF>F>F0F??(FEF>
F>F0F??(FGF>F>F0F??(FIF>F>F0F??(FepF>F>F0F?C$>&FM6,F4FQF=F=FAFCFEFGFIFepFR>&FM6
,F4FQF=FAFCFCFEFGFIFepFR?(F=F>F>FWF??(FAFZF>F0F??(FCF>F>FWF??(FgnFhnF>F0F??(FEF
>F>F0F??(FGF>F>F0F??(FIF>F>F0F??(FepF>F>F0F?C$@$F6C&>&FM6,F4FQF=FAFgnFCFEFGFIFe
p,$&FM6,F4FQF=FAFCFgnFEFGFIFepFX>&FM6,F4FQFAF=FCFgnFEFGFIFepFibl>&FM6,F4FQFAF=F
gnFCFEFGFIFepFjbl>Fjbl-F;6$F^p7*F=FAFCFgnFEFGFIFep-Fap6%F^pFeclFOFcpF-FdpF-F-,
I)readfileR6#%)filenameGF-F-F-C%-%'printfG6#((%)Reading~GF^p%%~...GA((%!GFf`lF^
p-F^dl6#%(~done.|+GF-F-F-F-,
I-grF_calc_d3RRFjp6+FbqFcqFdqFeq%#g1G%#g2GFfqF)F&F-F-C'>F^r%:grG_Ricciscalarcdn
cdncdn_G>F[sF1>FirFR?(F0F>F>F[sF??(FbsF>F>F[sF?@$Fd_l?(FesF>F>F[sF??(FgsF>F>F[s
F?@$Fj_l?(F`rF>F>F[sF??(FbrF>F>F[sF?@$Fdr>Fir,&FirF>*,Fe_lF>F[`lF>FerF>&F^r6&F4
F0FesF`rF>&F^r6&F4FbsFgsFbrF>F>-Fat6#FirF-F-F-F-,
I-grF_calc_d4RRFjp6-FbqFcqFdqFeqF^elF_el%#h1G%#h2GFfqF)F&F-F-C'>Fiq%=grG_Riccis
calarcdncdncdncdn_G>F\rF1>F^rFR?(F0F>F>F\rF??(FbsF>F>F\rF?@$Fd_l?(FesF>F>F\rF??
(FgsF>F>F\rF?@$Fj_l?(F`rF>F>F\rF??(FbrF>F>F\rF?@$Fdr?(FirF>F>F\rF??(F[sF>F>F\rF
?@$F]s>F^r,&F^rF>*.Fe_lF>F[`lF>FerF>F^sF>&Fiq6'F4F0FesF`rFirF>&Fiq6'F4FbsFgsFbr
F[sF>F>-Fat6#F^rF-F-F-F-,
I0grF_calc_d4RiemRFjp61F^qF_qF`qFaqFbqFcqFdqFeqF^elF_elFjflF[glFfqF)F&F-F-C'>81
F1>80FR>82%;grG_Rdndnupupcdncdncdncdn_G?(F`rF>F>F[ilF??(FbrF>F>F[ilF?@$Fdr?(Fir
F>F>F[ilF??(F[sF>F>F[ilF?@$F]s?(F^rF>F>F[ilF??(F\rF>F>F[ilF?@$0&Ffr6%F4F^rF\rFR
?(FiqF>F>F[ilF??(8/F>F>F[ilF?@$0&Ffr6%F4FiqF_jlFR?(F0F>F>F[ilF??(FbsFcsF>F[ilF?
?(FesF>F>F[ilF??(FgsFhsF>F[ilF?>F]il,&F]ilF>*.FerF>F^sF>F[jlF>FbjlF>&F_il6+F4F0
FbsFesFgsF`rFirF^rFiqF>&F_il6+F4FesFgsF0FbsFbrF[sF\rF_jlF>F>-Fat6#,$F]ilFdtF-F-
F-F-,
I1grF_calc_diRicciRFjp6)F^qF_qF`qFaqF&FfqF2F+F-C'>F`r&&%+grG_ObjDefG6#F^p6#F]w>
FbrFR>Fir(FirF4?(F0F>F>FirF??(FbsF>F>FirF??(FesF>F>FirF??(FgsF>F>FirF?>Fbr,&Fbr
F>*(F[`lF>&F`r6&F4F0FbsFesF>&F`r6&F4FbsF0FgsF>F>-Fat6#FbrF-F-F-F-,
I*interfaceR6"6&%"rG%"vG%#naG%#vaG6#%]oCopyright~(c)~1999~by~the~Waterloo~Maple
~Inc.~All~rights~reserved.GF^]mC&@$4-%%typeG6$7#9".%.interfaceargsGYQ2invalid~a
rgumentsF^]m>8$Fcp?&8%F\^mF?@%-Fj]m6$Fe^mFh]l@'/Fe^m.%+patchlevelGC$>8'-F\_mF^]
m@%/F__m-F[_mF^]m>Fc^m6$Fc^mFR>Fc^m6$Fc^mF__m/Fe^m.%+autoassignG>Fc^m6$Fc^m%5in
terface/autoassignG>Fc^m6$Fc^m-%+streamcallG6#-%.INTERFACE_GETG6#Fe^mC%>8&-%#op
G6$F>Fe^m>F__m-Fj`m6$""#Fe^m@'/Fh`mF[_mY6$Q1%1~cannot~be~setF^]mFh`m/Fh`mFi_mC$
@$4-Fj]m6$F__m%'symbolGYQAautoassign~root~must~be~a~symbolF^]m@'-%'memberG6$F__
m<$Fgt.%%noneG-%'assignG6#/.F]`mFdbm/F__mF?-Ffbm6#/Fibm.F[y-Ffbm6#/FibmF__m-Fa`
m6#-%.INTERFACE_SETG6$Fh`mF__mOFc^mF^]m6#F\_mF^]mFh^l,
I'printfR6"F[dm6#F`^lF[dmC%-F\^l6$%(defaultG9"-%'fflushG6#F`dmFcp6#%]oPrints~ex
pressions~to~the~default~output~based~on~a~format~string.GF[dmF[dmFh^l,
I0grF_calc_d3RiemRFjp6/F^qF_qF`qFaqFbqFcqFdqFeqF^elF_elF&FfqF)F-F-C'>F]ilF1>F_j
lFR>Fiq%8grG_Rdndnupupcdncdncdn_G?(F`rF>F>F]ilF??(FbrF>F>F]ilF?@$Fdr?(FirF>F>F]
ilF??(F[sF>F>F]ilF?@$F]s?(F^rF>F>F]ilF??(F\rF>F>F]ilF?@$Fjil?(F0F>F>F]ilF??(Fbs
FcsF>F]ilF??(FesF>F>F]ilF??(FgsFhsF>F]ilF?>F_jl,&F_jlF>*,FerF>F^sF>F[jlF>&Fiq6*
F4F0FbsFesFgsF`rFirF^rF>&Fiq6*F4FesFgsF0FbsFbrF[sF\rF>F>-Fat6#,$F_jlFdtF-F-F-F-,
I0grF_calc_diRiemRFjp6+F^qF_qF`qFaq%"eG%"fGF&FfqF2F+F-C'>FirFg[m>F[sFR>F^r(F^rF
4?(F`rF>F>F^rF??(FbrF>F>F^rF?@$Fdr?(F0F>F>F^rF??(FbsFcsF>F^rF??(FesF>F>F^rF??(F
gsFhsF>F^rF?>F[s,&F[sF>*(FerF>&Fir6(F4F0FbsFesFgsF`rF>&Fir6(F4FesFgsF0FbsFbrF>F
>-Fat6#,$F[sFdtF-F-F-F-,
I'fflushR6"Fchm6#F`^lFchm-Fb^l6$"#B9"6#%QFlushes~any~unwritten~data~to~the~phys
ical~file.GFchmFchmFh^l,
I'dinvarRF-F-F+F-C'>&%-grG_symmetryG6#%0grF_sym_D2MRiemG<$7$7(F_amF>""$Fdt""&""
'FX7$7(F>F_amFdtFfimFgimFhimFX>&F`im6#F"<$7$7)F_amF>FfimFdtFgimFhim""(FX7$7)F>F
_amFdtFfimFgimFhimFajmFX>&F`im6#Fh`l<$7$7*F_amF>FfimFdtFgimFhimFajm"")FX7$7*F>F
_amFdtFfimFgimFhimFajmFjjmFX-%'lprintG6#%8Differential~InvariantsG-F^[n6#%<Last
~modified~Jan.~20,~1995GF-6#F`imF-F-,
I0grF_sym_D2MRiemRF$F(F+F-C&>F0F1@$F6?(F=F>F>F0F??(FAF>F>F0F??(FCF>F>F0F??(FEF>
F>F0F??(FGF>F>F0F?C$>&FM6*F4FQF=F=FAFCFEFGFR>&FM6*F4FQF=FAFCFCFEFGFR?(F=F>F>FWF
??(FAFZF>F0F??(FCF>F>FWF??(FgnFhnF>F0F??(FEF>F>F0F??(FGF>F>F0F?C$@$F6C&>&FM6*F4
FQF=FAFgnFCFEFG,$&FM6*F4FQF=FAFCFgnFEFGFX>&FM6*F4FQFAF=FCFgnFEFGFb]n>&FM6*F4FQF
AF=FgnFCFEFGFc]n>Fc]n-F;6$F^p7(F=FAFCFgnFEFG-Fap6%F^pF^^nFOFcpF-FdpF-F-,
I,grF_calc_dRRFjp6'FbqFcqFfqF)F&F-F-C'>F`r%4grG_Ricciscalarcdn_G>FgsF1>FesFR?(F
0F>F>FgsF??(FbsF>F>FgsF?>Fes,&FesF>*(Fe_lF>&F`r6$F4F0F>&F`r6$F4FbsF>F>-Fat6#Fes
F-F-F-F-
