M6R0
I3type/interfaceargs-%%listG6#<$%%nameG/F'%)anythingG6",
I(fprintfR6"F-6#%^oCopyright~(c)~1994-1998~by~Waterloo~Maple~Inc.~All~rights~re
served.GF--%&iolibG6$""*9"6#%gnPrints~expressions~to~file~or~pipe~based~on~a~fo
rmat~string.GF-F-%*protectedG,
I(rootDir%/maple/grtools/G6",
I)grmixparR6#%%exprG6$%#ddG%&expr2G6#%boCopyright~1993~by~Waterloo~Maple~Softwa
re~-~slight~tweak~by~P.~MusgraveGF:@+509#"""4-%%typeG6$9$<%.%*algebraicG.F$.%)e
quationG-%&ERRORG6#%Bwrong~number~or~type~of~argumentsG-FK6$FMFR/-F;6#-%$lhsG6#
FM-F;6#-%$rhsGFin54-%$hasG6$FM%%diffG/FMFcoFM-FK6$FM.%)functionG@%/-%#opG6$""!F
MFcoC'>8$-F\p6$""#FM>8%-F\p6$FHFM?(F:FHFHF:3-FK6$FfpFgo/-F\p6$F^pFfpFcoC$>Fap6$
Fap-F\p6$FdpFfp>Ffp-F\p6$FHFfp>Ffp-F;6#Ffp-Fco6$Ffp-F\p6#-%%sortG6$7#Fap.%)lexo
rderG-%$mapG6$F;FMFerF:F:F:F:,
I)readfileR6#%)filenameGF:F:F:C%-%'printfG6#((%)Reading~GFM%%~...GA((%!GF8FM-F^
s6#%(~done.|+GF:F:F:F:,
I2help/text/grlimit-%%TEXTG6I%2HELP~FOR:~grlimitGFgs%aoCALLING~SEQUENCE:~grlimi
t(expr,var,limit,fnList,valueList,~<LHlimit>~)GFgs%FPARAMETERS:~expr~~~~~~-~an~
expressionG%J~~~~~~~~~~~~var~~~~~~~-~limiting~variableG%N~~~~~~~~~~~~limit~~~~~
-~limiting~value~of~varG%V~~~~~~~~~~~~fnList~~~~-~unspecified~functions~in~expr
G%_o~~~~~~~~~~~~valueList~-~values~of~functions~and/or~their~derivitivesG%U~~~~
~~~~~~~~~~~~~~~~~~~~w.r.t~var~at~the~limit~pointG%bo~~~~~~~~~~~~LHlimit~~~-~(op
tional)~limit~to~number~of~times~L'Hopital'sG%gn~~~~~~~~~~~~~~~~~~~~~~~~rule~sh
ould~be~applied~(default~=~8)GFgs%+SYNOPSIS:~GFgs%bo~-~evaluates~expr~at~the~li
mit~point.~If~indeterminate~forms~arise~thenG%bo~~~L'Hopital's~rule~is~applied~
(repeatedly)~until~the~limit~is~resolvedG%`o~~~or~LH_limit~is~exceeded.~If~LH_l
imit~is~exceeded~the~indeterminateG%B~~~portion~is~returned~unevalatedGFgs%_o~-
~grlimit~works~by~SUBSTITUTION~it~does~not~concern~itself~with~howG%O~~~rapidly
~functions~approach~the~limit~point.GFgs%_o~-~elements~of~valueList~must~consis
t~of~equations.~The~lhs~of~theseG%ao~~~must~be~a~STRING~containing~the~function
~at~the~limit~point.~DenoteG%^o~~~derivitives~w.r.t.~the~limiting~variable~by~a
~forward~quote~(').G%F~~~See~the~example~below~for~details.GFgs%_o~-~grlimit~fi
rst~expands~expression~and~then~evaluates~term~by~term.G%^o~~~divergent~terms~a
re~then~lumped~together,~factored~into~a~singleG%ao~~~expression~and~that~is~th
en~evaluated.~This~way~divergent~terms~canG%`o~~~cancel~in~some~cases.~If~the~f
inal~result~diverges~grlimit~returnsG%en~~~infinity~(regardless~of~whether~it's
~-infinity~or~not).GFgs%*EXAMPLES:G%jn#~if~expr~contains~a(r)~and~b(r)~and~limi
ting~values~at~r=0~areG%eo#~a(0)~=~b(0)~=~1~and~diff(b(0),r)~=~diff(a(0),r)~=~0
~then~the~command~is:G%bo>grlimit(expr,r,0,[a(r),b(r)],[`a(0)`=1,`a(0)'`=0,`b(0
)`=1,`b(0)'`=0]);GFgsF:,
I&pCostRF=6$%"aG%%costG6#%)rememberGF:C%>FfpF^p@.-FK6$FM%"*G?(FapFHFH-%%nopsGFi
n%%trueG>Ffp,&FfpFH-F]v6#-F\p6$FapFMFH-FK6$FM%"^G@%-FK6$Fbp%(numericG>Ffp*&FbpF
H-F]v6#FgpFHC$-%)pWarningG6$%?Order~of~term~ignores~exponentGFM>Ffp-&%(codegenG
FjqF^x-FK6$FM%"+G>Ffp-%$minG6#-%$seqG6$F`w/Fap;FHF[w-FK6$FMFjw>FfpF^p5Fjo/F[p%%
DiffG@$-%)assignedG6#&%-pexpandArrayG6#(%(diffBy_GFbp>Ffp,&F]xFHF^zFH-FK6$FM<%F
ho%*procedureGF'@$-F\z6#&F_zFin>FfpF\[lFfpF:F:F:F:,
I*interfaceR6"6&%"rG%"vG%#naG%#vaG6#%]oCopyright~(c)~1999~by~the~Waterloo~Maple
~Inc.~All~rights~reserved.GF`[lC&@$4-FK6$7#9".%.interfaceargsGYQ2invalid~argume
ntsF`[l>8$%%NULLG?&8%F]\lF]w@%-FK6$Fg\lF'@'/Fg\l.%+patchlevelGC$>8'-F^]lF`[l@%/
Fa]l-F]]lF`[l>Fd\l6$Fd\lF^p>Fd\l6$Fd\lFa]l/Fg\l.%+autoassignG>Fd\l6$Fd\l%5inter
face/autoassignG>Fd\l6$Fd\l-%+streamcallG6#-%.INTERFACE_GETG6#Fg\lC%>8&-F\p6$FH
Fg\l>Fa]l-F\p6$FdpFg\l@'/Fj^lF]]lY6$Q1%1~cannot~be~setF`[lFj^l/Fj^lF[^lC$@$4-FK
6$Fa]l%'symbolGYQAautoassign~root~must~be~a~symbolF`[l@'-%'memberG6$Fa]l<$%&fal
seG.%%noneG-%'assignG6#/.F_^lFe`l/Fa]lF]w-Fg`l6#/Fj`l.%"RG-Fg`l6#/Fj`lFa]l-Fc^l
6#-%.INTERFACE_SETG6$Fj^lFa]lOFd\lF`[l6#F^]lF`[lF7,
I)difftoolRF=6#%'retValGF:F:C%>FapFM@&-FK6$FM<%FivFfwFjx>Fap-Ffr6$F[blFM-FK6$FM
Fho@%Fjo@$-FK6$FgpFho@$/-F\p6$F^pFgpFco>Fap-%%subsG6$/FcoFiyFM>Fap-F[p6#-F\p6#-
Ffr6$F[bl7#-F\pFinFapF:F:F:F:,
I(pexpandRF=6%%(newExprGF^blF`vF:F:C'@&4-F\z6#%'pOrderG-FU6#%JPlease~assign~pOr
der~before~using~pexpandG4-F\z6#F_z-FU6#%IPlease~use~pdefine~before~using~pexpa
nd.G>Fap-%'expandGFin>FfpF^p@&-FK6$FapFjx?(8&FHFH-F\w6#FapF]w@$1-F]v6#-F\p6$F[f
lFapFidl>Ffp,&FfpFHFbflFH1-F]vF]flFidl>FfpFapFfpF:F:F:F:,
I(pdefineRF:6%F`v%"bG%&orderGF:F:C%@$3/FGFH4-FK6$&9"6#FHF$C$@'/Fegl.%&clearGC%>
F_z.F_z-%'forgetG6#F]v-Fahl6#F`dl/Fegl.%(displayG@%F^elC$-%&printGF_el-F[il6#/%
(pOrder~GFidl-F[il6#%0Nothing~definedG-FU6#%LParamater~must~be~clear,~display~o
r~a~list.G-%'RETURNG6#%&Done.G?(FapFHFHFGF]w@%-FK6$&FfglF]flF$C%@$4-FK6$&F^jlFg
glFjw-FU6#%CFirst~entry~in~a~list~must~numericG>F[flFdjl?(FfpFdpFH-F\w6#F^jlF]w
>&F_z6#&F^jlFjqF[fl-%'lprintG6%%*Argument~GF^jl%;~is~not~a~list~-~ignoring.G-Fa
[m6#%%DoneGF:F_elF:F:,
I'printfR6"Fj[m6#F/Fj[mC%-F+6$%(defaultG9"-%'fflushG6#F_\mFe\l6#%]oPrints~expre
ssions~to~the~default~output~based~on~a~format~string.GFj[mFj[mF7,
I(grtoolsRF:F:F:F:-Fa[m6#%8Last~built~27~May,~1999GF:F:F:F:,
I'fflushR6"F]]m6#F/F]]m-F16$"#B9"6#%QFlushes~any~unwritten~data~to~the~physical
~file.GF]]mF]]mF7,
I(grlimitRF:65F`vF\gl%"lG%$varG%&limitG%'fnListG%&indefG%)LH_limitG%)numtermsG%
$topG%$botG%%etopG%%ebotG%'resultG%%rootG%(subListG%$ticG%(diffSubG%"xGF:F:C;@$
2FG""%-FU6#%3Too~few~parametersG>86-Feel6#Fegl>8'&Ffgl6#Fdp>8(&Ffgl6#""$>8)&Ffg
l6#F\_m>83&Ffgl6#""&@$/F^`m7"-FU6#%TNo~implicit~functions.~Use~maple's~limit()~
instead.G>8+"")@$/FG""'>F]am&Ffgl6#Faam>85<"?(FapFHFH-F\w6#F^`mF]wC&>82-%(conve
rtG6$-Fdcl6$/Fe_mFi_m&F^`mF]fl%'stringG>84%"'G>Ffam-%&unionG6$Ffam<#/FdbmF]bm?(
FfpFHFH,&F]amFHFdpFHF]wC$>Ffam-F[cm6$Ffam<#/-Fco6$Fdbm-%"$G6$Fe_mFfp-%$catG6$F]
bmFgbm>Fgbm-F]dm6$FgbmFhbm>Fb`m7$-F\p6#Fb`mFcbm@%-FK6$Fa_mFjx>8,-F\w6#Fa_m>Fjdm
FH>81F^p>8*F^p?(FapFHFHFjdmF]wC(>F[flF^p>8/F^p>80F^p@%/FjdmFHC$>8--%&numerGF\em
>8.-%&denomGF\emC$>F]fm-F_fm6#-F\p6$FapFa_m>Fafm-FcfmFgfm?(F:FHFHF:33/FfemF^p/F
hemF^p1F[flF]amC'>Ffem-%%evalG6#-Fdcl6$Fb`m-Fdcl6$FfamF]fm>Fhem-Fegm6#-Fdcl6$Fb
`m-Fdcl6$FfamFafm>F]fm-Fco6$F]fmFe_m>Fafm-Fco6$FafmFe_m>F[fl,&F[flFHFHFH@(1F]am
F[flC%-F[il6#%aoLHopital~limit~reached~and~still~indeterminate.~Leaving~term~un
alteredG>F_em,&F_emFHFhfmFH\F`gm>Faem,&FaemFHFhfmFH0FfemF^p>F_em,&F_emFH*&FfemF
HFhem!""FH>Faem-%'factorG6#Faem>F[flF^p>FfemF^p>FhemF^p>F]fm-F_fmF]jm>Fafm-Fcfm
F]jm?(F:FHFHF:F]gmC'>FfemFdgm>FhemF\hm>F]fmFchm>FafmFfhm>F[flFihm@(F[imC$-F[il6
#%PLHopital~limit~reached~and~still~indeterminate.G>F_em,&F_emFHFaemFHF`gm>F_em
%)infinityGFeim>F_emFgimF_emF:F:F:F:
