M6R0
I9simplify/trigsin/recurseR6#%"xG6$%"aG%"nG6#%JCopyright~1993~by~Waterloo~Maple
~SoftwareG6"@)-%%typeG6$9$%)functionGC%>8%-%#opG6$""!F0>8$-%$mapG6$%1simplify/t
rigsinG7#-F66#F0-F46#-F66#F:3-F.6$F0%"^G4-F.6$-F66$""#F0%(integerG)-F>6#-F66$""
"F0-F>6#FM-F.6$F0<%%"*GFI%"+G-F<6$9!F0F0F+F+F+F+,
I3type/interfaceargs-%%listG6#<$%%nameG/F`o%)anythingG6",
I(fprintfR6"Ffo6#%^oCopyright~(c)~1994-1998~by~Waterloo~Maple~Inc.~All~rights~r
eserved.GFfo-%&iolibG6$""*9"6#%gnPrints~expressions~to~file~or~pipe~based~on~a~
format~string.GFfoFfo%*protectedG,
I(rootDir%/maple/trigsin/GF+,
I)readfileR6#%)filenameGF+F+F+C%-%'printfG6#((%)Reading~GF0%%~...GA((%!GFapF0-F
ip6#%(~done.|+GF+F+F+F+,
I,trigsin/cosR6#F(F+6$%)rememberGF*E\s#F8FVFV-%$cosG6#%#_XG-%'expandG6#*&,&FVFV
*$-%$sinGF^rFO!""FV-Ffq6#,&F0FV!"#FVFVF+F+F+F+,
I$cosR6#'F%%*algebraicG6$F(%"tG6#%aoCopyright~(c)~1992~by~the~University~of~Wat
erloo.~All~rights~reserved.GE\s+F8FV,$%#PiG#FV""%,$*$FO#FVFOF]t,$%)infinityGFhr
%*undefinedGF_tF`tFhsFhrF_rF\r,$Fhs#FV""',$*$""$F]tF]t,$FhsF]tF8^#FV-%%coshG6#F
V,$Fhs#FVFftF]t@A09#FVY6$Q=expecting~1~argument,~got~%16"F`u-F.6$9$.-%(complexG
6#%&floatG-%&evalfG6#-.F]r6#Fgu-F.6$Fgu.F_t@%-F.6$-%#ReGFbvFev*&FguFVF`tFV*$Fgu
Fjs-F.6$Fgu.F`t@%-F.6$Fgu.%*imaginaryG-%#ImGFbvF[w3-F.6$Fgu.%1SymbolicInfinityG
/-%*traperrorG6#-%#isG6$Fgu%%realG%%trueGF`t5Faw3-F.6$FguFfn-%'memberG6$Fdx-F<6
%F.<#-F6FbvFcw-Fjt6#*&^#FhrFVFguFV-F.6$Fgu.-Fju6#%(numericG@%2-%%csgnGFbvF8-F]r
6#,$FguFhrF`v33Fgx-F.6$-F66$FVFguFfy2-F]z6#FezF8F^z3Fgx-F.6$Fgu.-%#&*G6$%)ratio
nalG-%*identicalG6#FhsC$>8%Fez@)2Fg[l#FVFOF`v2Fg[lFV,$-F]r6#*&,&FVFVFg[lFhrFVFh
sFVFhr2Fg[lFO-F]r6#*&,&FOFVFg[lFhrFVFhsFV-F]r6#*&,&Fg[lFV-%%iquoG6$-%&truncG6#F
g[lFOF\sFVFhsFV3-F.6$FguFgn/-F^x6#-%%signGFbvFhrF^z3Fa]l-%$hasG6$FguFhsC$>Fg[l-
F<6$R6#F%FduFduFdu@$-F.6$*&FguFVFhsFhr.Fa[lFe^lFduFduFduF^y@%/-%%nopsGF_]lFVC$>
Fg[l-F6F_]l@+2Fg[lF8-F]r6#,(FguFV*&FhsFV-F^]l6#,$Fg[lFj[lFVF\sFhsFOFi[l>-F]rFbv
F`vF[\l,$-Fgr6#,&FguFVFhs#FhrFOFhrFa\l,$-F]r6#,&FguFVFhsFhrFhr-F]r6#,&FguFVFc_l
F\s>Fh_lF`v33Fgx-Fjx6%Fhs7#F_y.8$/FewF8C%>Fg[l-%'subsopG6$/F\alFVFgu>F\al-%%fra
cGF_]l@+/-FfalFe_lF8FV/-Ffal6#,&Fg[lFj[lF]`lFVF8Fhr/F\alF8)FhrFg[l/-Ffal6#,&Fg[
lFVF]`lFVF8F8>Fh_lF`v3-F.6$Fgu.F1/-Fj^lFbvFVC%>F\al-F66$F8Fgu>Fg[lFez@//F\al.%'
arcsinG-%%sqrtG6#,&FVFV*$Fg[lFOFhr/F\al.%'arccosGFg[l/F\al.%'arctanG*$-Fecl6#,&
FVFVFhclFVFhr/F\al.%'arccscG-Fecl6#,&FVFV*$Fg[lF\sFhr/F\al.%'arcsecG*$Fg[lFhr/F
\al.%'arccotG*&Fg[lFVF`dlFhr>Fh_lF`v-F.6$Fgu-.%)specfuncG6$.Fbo.%)JacobiAMG-%)J
acobiCNG6#F_y-F.6$Fgu.-F^dl6$FasFas*&-F66$FOFguFV-Fecl6#,&*$FezFOFV*$FeflFOFVFh
r>Fh_lF`vFduFduFduF`p,
I*interfaceR6"6&%"rG%"vG%#naG%#vaG6#%]oCopyright~(c)~1999~by~the~Waterloo~Maple
~Inc.~All~rights~reserved.GF_glC&@$4-F.6$7#9".%.interfaceargsGYQ2invalid~argume
ntsF_gl>8$%%NULLG?&8%F\hlFdx@%-F.6$FfhlF`o@'/Ffhl.%+patchlevelGC$>8'-F]ilF_gl@%
/F`il-F\ilF_gl>Fchl6$FchlF8>Fchl6$FchlF`il/Ffhl.%+autoassignG>Fchl6$Fchl%5inter
face/autoassignG>Fchl6$Fchl-%+streamcallG6#-%.INTERFACE_GETG6#FfhlC%>8&-F66$FVF
fhl>F`il-F66$FOFfhl@'/FijlF\ilY6$Q1%1~cannot~be~setF_glFijl/FijlFjilC$@$4-F.6$F
`il%'symbolGYQAautoassign~root~must~be~a~symbolF_gl@'-Fjx6$F`il<$%&falseG.%%non
eG-%'assignG6#/.F^jlFc\m/F`ilFdx-Fe\m6#/Fh\m.%"RG-Fe\m6#/Fh\mF`il-Fbjl6#-%.INTE
RFACE_SETG6$FijlF`ilOFchlF_gl6#F]ilF_glF`p,
I6type/SymbolicInfinityR6#%"eG6"6%Fjq%'systemG%ipCopyright~(c)~1993~Gaston~Gonn
et,~Wissenschaftliches~Rechnen,~ETH~Zurich.~All~rights~reserved.GE\s"F_rFa\m-%&
evalbG6#5-F.6$9$F_t3-F.6$Fh^mFfn-Fjx6$Fdx-F<6%F.<#-F66#Fh^mF_tF]^mF]^mF]^mF]^m,
I(trigsinRF+F+F+F+-%'lprintG6#%8Last~built~27~May,~1999GF+F+F+F+,
I'printfR6"F[`m6#FhoF[`mC%-Fdo6$%(defaultG9"-%'fflushG6#F``mFdhl6#%]oPrints~exp
ressions~to~the~default~output~based~on~a~format~string.GF[`mF[`mF`p,
I/trigsin/normalR6#F'6%%"pG%"sGF%6%FjqF_^mF*F+C*>F:--%(readlibG6#%-trig/polynom
GFA@$/F:%%FAILG-%'RETURNG6#-%.trigsin/identGFA>8&&F:6#FO>F4&F:6#Fft>F:&F:F[u@$-
Fj]l6$F:F]r>F:-%%premG6%F:,(*$-F]r6#F^bmFOFV*$-FgrF`cmFOFVFhrFVF_cm@$-Fj]l6$F:F
jt>F:-F[cm6%F:,(*$-FjtF`cmFOFV*$-%%sinhGF`cmFOFhrFhrFVF[dm-%%subsG6$/F^bm*&F^bm
FVF4FhrF:F+F+F+F+,
I1simplify/trigsinRFi`m6-%#c0G%#c1G%"fG%#f1GF(%#n1G%"dG%#d1GF\am%"SG%&StrigGF]a
mF+C2@&-F.6$F0-%(ratpolyG6#Fa[l-FiamFA-F.6$F0<&.%)equationG.%&rangeG.F]o.%$setG
-Fiam6#-F<6$%.simplify/trigGF0>F^bm-%(convertG6$F0%'sincosG>F^bm-F"F`cm>F^bm-%0
simplify/normalGF`cm>8(-%)frontendG6$Far7#-%&numerGF`cm>8*-Fdgm6$Far7#-%&denomG
F`cm>Fbgm-Fg`m6#Fbgm>Fjgm-Fg`m6#Fjgm>F^bm-Fdgm6$F`gm7#*&FbgmFVFjgmFhr>FjgmF^hm>
FbgmFggm>8--%&minusG6$-%'indetsG6$Fjgm.F`o-Fcim6$-%'selectG6%F.-Fcim6$Fjgm.%'Ro
otOfG.%'algfunGFeim>8.-Fcim6$Fjgm.%%trigG>Fbjm-Fiim6$R6#%"yGF+6$%)operatorG%&ar
rowGF+-Fjx6$F5<$.F]r.FjtF+F+F+Fbjm?&8,FbjmFdx@$-F.6$Fjgm-%(polynomG6$.FboFf[nC$
>8+-%(collectG6$FjgmFf[n@$/-%'degreeG6$F`\nFf[nFVC)>F4-%&coeffG6%F`\nFf[nFV>F:-
F\]n6%F`\nFf[nF8@$0-%'testeqG6#,&*&F4FVFf[nFVFVF:FhrFa\m@%334-F.6$Ff[n%)constan
tG-F.6$F4-F[\n6$F_jmF^im-F.6$F:Fa^n@$/-F^x6#-%&evalaG6#-%'ExpandG6#*$Ff]nFhr%*l
asterrorG\Fa_n@%/-F66$F8Ff[nFc[n>F`\n-%)simplifyG6#,&*&F4FO,&FVFV*$-Fgr6#-F66$F
VFf[nFOFhrFVFV*$F:FOFhr>F`\n-Fh_n6#,&*&F4FO,&*$-F^dmF_`nFOFVFVFVFVFVFb`nFhr>8)-
Fh_n6$*&FbgmFVFf]nFV.Fc_m>8'-Fdgm6$F`gm7#*&F\anFVF`\nFhr@$2-%'lengthG6#Fban-Fja
nF`cmC%>F^bmFban>FjgmF^hm>FbgmFggmF^bmF+F+F+F+,
I.trigsin/identRFi`mF$F]amF+@+4-Fj]l6$F0.7&FgrF]rF^dmFjtF0-F.6$F0FfnC$>F:-Fdgm6
$Far7#-F<6$F\bmF0@%/F:F0F:-F\bmFEFG@)FJF03-F.6$FTF1/-F66$F8FTF]r-F`dm6$/F_r-F66
$FVFT-FfqFX3Fgcn/FjcnFjt-F`dm6$F^dn-%-trigsin/coshGFXF0-F.6$F0FgnFhnF0F+F+F+F+,
I'fflushR6"F\en6#FhoF\en-Fjo6$"#B9"6#%QFlushes~any~unwritten~data~to~the~physic
al~file.GF\enF\enF`p,
I-trigsin/coshRFhqF+FiqE\s#F8FVFV-FjtF^r-Far6#*&,&*$-F^dmF^rFOFVFVFVFV-FgdnFjrF
VF+F+F+F+,
I%coshR6#'F%Fas6$F(Fcs6#FesE\s%F8FVF_tF_tF_rFgenFht-F]rF[u@909#FVY6$%=expecting
~1~argument,~got~%1GFifn-F.6$9$.-FjuF[v-F^v6#-.Fjt6#F_gn-F.6$F_gn.F_t@%-F.6$-Ff
wFfgnFign*&F_gnFVF`tFV*$F_gnFO-F.6$F_gn.F`tF^hn3-F.6$F_gn.F[x/-F^x6#-Fax6$F_gnF
cxFdxF_t5-F.6$F_gn.Fdw3-F.6$F_gnFfn-Fjx6$Fdx-F<6%F.<#-F6FfgnF_in-F]r6#*&^#FhrFV
F_gnFV-F.6$F_gn.-FjuFhy@%2-F]zFfgnF8-Fjt6#,$F_gnFhrFdgn33Fain-F.6$-F66$FVF_gnF_
jn2-F]z6#F[[oF8Fdjn3-F.6$F_gnFgn/-F^x6#-Fg]lFfgnFhrFdjn3Fa[o-Fj]l6$F_gnFhsC$>8%
-F<6$R6#F%6"Fa\oFa\o@$-F.6$*(F\jnFVF_gnFVFhsFhr.Fa[lFe\oFa\oFa\oFa\oFgin@%/-Fj^
l6#F\\oFVC$>F\\o-F6Fj\o@+2F\\oF8-Fjt6#,(F_gnFV*(^#F\sFVFhsFV-F^]l6#,$F\\o#FVFOF
VFV*&^#FOFVFhsFVFV2F\\oFh]o>-FjtFfgnFdgn2F\\oFV*&^#FVFV-F^dm6#,&F_gnFV*&^##FhrF
OFVFhsFVFVFV2F\\oFO,$-Fjt6#,&F_gnFV*&F\jnFVFhsFVFVFhr-Fjt6#,&F_gnFVFc]oFV>F]^oF
dgn3-F.6$F_gn.F1/-Fj^lFfgnFVC%>8$-F66$F8F_gn>F\\oF[[o@1/Fi_o.%(arcsinhG-Fecl6#,
&*$F\\oFOFVFVFV/Fi_o.%(arccoshGF\\o/Fi_o.%(arctanhG*$-Fecl6#,&FVFVFd`oFhrFhr/Fi
_o.%(arccschG-Fecl6#,&FVFV*$F\\oF\sFV/Fi_o.%(arcsechG*$F\\oFhr/Fi_o.%(arccothG*
(F\\oFV-Fecl6#,&F\\oFVFVFVFhr-Fecl6#,&F\\oFVFhrFVFhr/Fi_o.%#lnG,&F\\oFh]oFiaoFh
]o>F]^oFdgn>F]^oFdgnFa\oFa\oFa\oF`p
